// Restored from ref/webview/assets/local-conversation-thread-C3pAiUmg.js
// Local conversation thread public barrel.
// Stage-3 kebab directory: LocalThreadSurface + peer siblings (timeline /
// VirtualizedTurnList / turn-list-entry groveR1 / composer footer /
// pending-worktree / resume / header / summary / realtime); soft ensure-inits
// remain throws: 0. Mechanical body under
// `.deobfuscate-javascript/_full/files/local-conversation-thread-C3pAiUmg/`.

export { localConversationThreadI } from "./path-contains-worktrees";

export {
  ResourceProviderIcon,
  ResourceProviderIcon as localConversationThreadL,
  ResourceProviderIcon as localConversationThreadUpperL,
  ResourceProviderIcon as LocalConversationThreadUpperL,
  type ResourceProviderIconProps,
  type ResourceProviderIconResource,
} from "./resource-provider-icon";

export {
  LocalThreadSurface,
  LocalThreadSurface as LocalConversationThreadUpperI,
  LocalThreadSurface as localConversationThreadUpperI,
  LocalThreadSurface as _localConversationThreadI,
  type LocalThreadSurfaceProps,
} from "./local-thread-surface";

export {
  localConversationThreadA,
  localConversationThreadD,
  localConversationThreadH,
  localConversationThreadJ,
  localConversationThreadM,
  type DisabledReasonProps,
  type PrCommentAttachArgs,
  type PrCommentFocusArgs,
  type PrCommentGuidanceArgs,
} from "./pr-helpers";

export {
  localConversationThreadUpperA,
  localConversationThreadUpperB,
  localConversationThreadUpperC,
  localConversationThreadUpperD,
  localConversationThreadUpperE,
  localConversationThreadUpperF,
  localConversationThreadUpperM,
  localConversationThreadUpperO,
  localConversationThreadUpperP,
  localConversationThreadUpperR,
  localConversationThreadUpperS,
  localConversationThreadUpperT,
  ensureLocalConversationThreadInit,
  ensureLocalConversationThreadUpperNInit,
  localConversationThreadB,
  localConversationThreadC,
  localConversationThreadE,
  localConversationThreadF,
  localConversationThreadG,
  localConversationThreadK,
  localConversationThreadN,
  localConversationThreadO,
  localConversationThreadP,
  localConversationThreadR,
  localConversationThreadS,
  localConversationThreadT,
  localConversationThreadUnderscore,
  localConversationThreadU,
  localConversationThreadV,
  localConversationThreadW,
  localConversationThreadX,
  localConversationThreadY,
  localConversationThreadZ,
  _localConversationThreadA,
  _localConversationThreadB,
  _localConversationThreadC,
  _localConversationThreadF,
  _localConversationThreadL,
  _localConversationThreadM,
  _localConversationThreadO,
  _localConversationThreadP,
  _localConversationThreadR,
  _localConversationThreadS,
  _localConversationThreadT,
  bindLocalConversationThreadUpperA,
  bindLocalConversationThreadUpperB,
  bindLocalConversationThreadUpperC,
  bindLocalConversationThreadUpperD,
  bindLocalConversationThreadUpperE,
  bindLocalConversationThreadUpperF,
  bindLocalConversationThreadUpperI,
  bindLocalConversationThreadUpperL,
  bindLocalConversationThreadUpperM,
  bindLocalConversationThreadUpperO,
  bindLocalConversationThreadUpperP,
  bindLocalConversationThreadUpperR,
  bindLocalConversationThreadUpperS,
  bindLocalConversationThreadUpperT,
  bindLocalConversationThreadUnderscore,
  bindLocalConversationThreadA,
  bindLocalConversationThreadB,
  bindLocalConversationThreadC,
  bindLocalConversationThreadD,
  bindLocalConversationThreadF,
  bindLocalConversationThreadG,
  bindLocalConversationThreadH,
  bindLocalConversationThreadI,
  bindLocalConversationThreadJ,
  bindLocalConversationThreadK,
  bindLocalConversationThreadL,
  bindLocalConversationThreadM,
  bindLocalConversationThreadO,
  bindLocalConversationThreadP,
  bindLocalConversationThreadR,
  bindLocalConversationThreadS,
  bindLocalConversationThreadT,
  bindLocalConversationThreadU,
  bindLocalConversationThreadV,
  bindLocalConversationThreadW,
  bindLocalConversationThreadX,
  bindLocalConversationThreadY,
  bindLocalConversationThreadZ,
  bindBindLocalConversationThreadExport,
  bindLocalConversationThreadExport,
} from "./runtime-bridges";
