// Restored from ref/webview/assets/local-conversation-thread-C3pAiUmg.js
// Soft bridges barrel: ensure-inits + surface/peer/turn-list accessors.
// Thin re-export only (no splitRequired). throws: 0.

export {
  localConversationThreadUpperA,
  localConversationThreadUpperR,
  ensureLocalConversationThreadInit,
  ensureLocalConversationThreadUpperNInit,
  localConversationThreadB,
  localConversationThreadC,
  localConversationThreadE,
  localConversationThreadF,
  localConversationThreadG,
  localConversationThreadK,
  localConversationThreadN,
  localConversationThreadO,
  localConversationThreadP,
  localConversationThreadR,
  localConversationThreadS,
  localConversationThreadT,
  localConversationThreadUnderscore,
  localConversationThreadU,
  localConversationThreadV,
  localConversationThreadW,
  localConversationThreadX,
  localConversationThreadY,
  localConversationThreadZ,
  _localConversationThreadA,
  _localConversationThreadB,
  _localConversationThreadC,
  _localConversationThreadF,
  _localConversationThreadL,
  _localConversationThreadM,
  _localConversationThreadO,
  _localConversationThreadP,
  _localConversationThreadR,
  _localConversationThreadS,
  _localConversationThreadT,
  localConversationThreadUpperB,
  localConversationThreadUpperC,
  localConversationThreadUpperD,
  localConversationThreadUpperE,
  localConversationThreadUpperF,
  localConversationThreadUpperM,
  localConversationThreadUpperO,
  localConversationThreadUpperP,
  localConversationThreadUpperS,
  localConversationThreadUpperT,
  bindLocalConversationThreadUpperA,
  bindLocalConversationThreadUpperB,
  bindLocalConversationThreadUpperC,
  bindLocalConversationThreadUpperD,
  bindLocalConversationThreadUpperE,
  bindLocalConversationThreadUpperF,
  bindLocalConversationThreadUpperI,
  bindLocalConversationThreadUpperL,
  bindLocalConversationThreadUpperM,
  bindLocalConversationThreadUpperO,
  bindLocalConversationThreadUpperP,
  bindLocalConversationThreadUpperR,
  bindLocalConversationThreadUpperS,
  bindLocalConversationThreadUpperT,
  bindLocalConversationThreadUnderscore,
  bindLocalConversationThreadA,
  bindLocalConversationThreadB,
  bindLocalConversationThreadC,
  bindLocalConversationThreadD,
  bindLocalConversationThreadF,
  bindLocalConversationThreadG,
  bindLocalConversationThreadH,
  bindLocalConversationThreadI,
  bindLocalConversationThreadJ,
  bindLocalConversationThreadK,
  bindLocalConversationThreadL,
  bindLocalConversationThreadM,
  bindLocalConversationThreadO,
  bindLocalConversationThreadP,
  bindLocalConversationThreadR,
  bindLocalConversationThreadS,
  bindLocalConversationThreadT,
  bindLocalConversationThreadU,
  bindLocalConversationThreadV,
  bindLocalConversationThreadW,
  bindLocalConversationThreadX,
  bindLocalConversationThreadY,
  bindLocalConversationThreadZ,
  bindBindLocalConversationThreadExport,
  bindLocalConversationThreadExport,
} from "./ensure-init-bridges";

export {
  type PendingWorktreeLaunch,
  bindSoftReadClientThreadId,
  bindSoftIsClientThreadEligibleForStableWorktree,
  bindSoftReadPendingWorktreeLaunch,
  bindSoftReadRouteConversationId,
  bindSoftReadHasConversation,
  bindSoftReadHostIdForConversation,
  bindSoftReadIsBackgroundSubagentsEnabled,
  bindSoftReadCachedHistoryPresent,
  bindSoftReadIsRealtimeVoiceThread,
  bindSoftReadRightPanelHidesThread,
  bindSoftThreadContentShift,
  bindSoftReadHotkeyHomePath,
  bindSoftShowConversationNotFoundToast,
  bindSoftMarkThreadVisible,
  softReadClientThreadId,
  softIsClientThreadEligibleForStableWorktree,
  softReadPendingWorktreeLaunch,
  softReadHasConversation,
  softReadHostIdForConversation,
  softReadRouteConversationId,
  softReadIsBackgroundSubagentsEnabled,
  softReadCachedHistoryPresent,
  softReadIsRealtimeVoiceThread,
  softReadRightPanelHidesThread,
  softThreadContentShift,
  softReadHotkeyHomePath,
  softShowConversationNotFoundToast,
  softMarkThreadVisible,
} from "./soft-surface-accessors";

export {
  type TurnTimelineLoadingKind,
  type RealtimeVoicePresentationState,
  softReadConversationNeedsResume,
  softMaybeResumeConversation,
  softIsResumeAutoRetryable,
  softShouldShowResumeErrorToast,
  softFormatResumeErrorMessage,
  softShowResumeErrorToast,
  softReadIsHotkeyWindow,
  softReadIsWindowActive,
  softReadThreadHasConversation,
  softReadParentConversationId,
  softReadThreadTitle,
  softReadAgentNickname,
  softResolveConversationMarkdown,
  softReadSummaryPanelShouldShow,
  softReadSummaryPanelShouldHideInline,
  softReadRealtimeVoicePresentationState,
  softRequestDetachRealtimePresentation,
  softMarkRealtimeVoiceHandoffComplete,
  softReadHostConnectionStatus,
  softReadRouteMatchesConversation,
  softReadIsResponseInProgress,
  softReadComposerModeAvailability,
  softReadLocalWorkspaceMaterialization,
  softSetRightPanelConversationFocus,
  softReadPendingWorktreeConversationState,
  softIsPendingWorktreeCancelling,
  softIsPendingWorktreePhaseCancellable,
  softClearPendingWorktreeAttention,
  softSetPendingWorktreePinned,
  softCancelPendingWorktree,
  softContinuePendingWorktreeLocally,
  softRetryPendingWorktree,
  softRetryPendingWorktreeConversationStart,
  softContinuePendingWorktree,
  softStartPendingWorktreeAutoFix,
  softReadIsConversationPresent,
  softReadHasRenderableTurns,
  softReadTurnTimelineLoadingKind,
  softReadAutomationBannerForThread,
  softMarkAutomationItemRead,
} from "./soft-peer-accessors";

export {
  softReadTurnListEntries,
  softWriteTurnListEntries,
  softReadVirtualizedTurnListScrollState,
  softWriteVirtualizedTurnListScrollState,
  softReadLatestTurnPhaseForEntity,
  softReadEntityTurn,
  softWriteEntityTurn,
  softRenderTurnListEntry,
  bindSoftReadTurnListEntries,
  bindSoftReadLatestTurnPhaseForEntity,
  bindSoftReadEntityTurn,
  type TurnListEntry,
  type LatestTurnPhaseInfo,
  type VirtualizedTurnListPersistedScrollState,
} from "./soft-turn-list-accessors";
