// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Protobuf analytics enums for in-app browser surface actions (IT/MQn/NQn).

/** Bundle `IT` / export `L6` — browser surface action type. */
export const CodexBrowserSurfaceActionType = {
  CODEX_BROWSER_SURFACE_ACTION_TYPE_UNSPECIFIED:
    "CODEX_BROWSER_SURFACE_ACTION_TYPE_UNSPECIFIED",
  CODEX_BROWSER_SURFACE_ACTION_TYPE_CAPTURE_SCREENSHOT_SELECTED:
    "CODEX_BROWSER_SURFACE_ACTION_TYPE_CAPTURE_SCREENSHOT_SELECTED",
  CODEX_BROWSER_SURFACE_ACTION_TYPE_SHOW_DEVICE_TOOLBAR_SELECTED:
    "CODEX_BROWSER_SURFACE_ACTION_TYPE_SHOW_DEVICE_TOOLBAR_SELECTED",
  CODEX_BROWSER_SURFACE_ACTION_TYPE_PASSWORD_MANAGER_SELECTED:
    "CODEX_BROWSER_SURFACE_ACTION_TYPE_PASSWORD_MANAGER_SELECTED",
  CODEX_BROWSER_SURFACE_ACTION_TYPE_CONTACT_INFO_SELECTED:
    "CODEX_BROWSER_SURFACE_ACTION_TYPE_CONTACT_INFO_SELECTED",
  CODEX_BROWSER_SURFACE_ACTION_TYPE_DOWNLOADS_SELECTED:
    "CODEX_BROWSER_SURFACE_ACTION_TYPE_DOWNLOADS_SELECTED",
  CODEX_BROWSER_SURFACE_ACTION_TYPE_EXTENSIONS_SELECTED:
    "CODEX_BROWSER_SURFACE_ACTION_TYPE_EXTENSIONS_SELECTED",
  CODEX_BROWSER_SURFACE_ACTION_TYPE_HISTORY_SELECTED:
    "CODEX_BROWSER_SURFACE_ACTION_TYPE_HISTORY_SELECTED",
  CODEX_BROWSER_SURFACE_ACTION_TYPE_BROWSER_SETTINGS_SELECTED:
    "CODEX_BROWSER_SURFACE_ACTION_TYPE_BROWSER_SETTINGS_SELECTED",
  CODEX_BROWSER_SURFACE_ACTION_TYPE_SITE_SETTINGS_SELECTED:
    "CODEX_BROWSER_SURFACE_ACTION_TYPE_SITE_SETTINGS_SELECTED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexBrowserSurfaceActionTypeName =
  (typeof CodexBrowserSurfaceActionType)[keyof typeof CodexBrowserSurfaceActionType];

/** Bundle `MQn` / export `F6` — browser surface id. */
export const CodexBrowserSurface = {
  CODEX_BROWSER_SURFACE_UNSPECIFIED: "CODEX_BROWSER_SURFACE_UNSPECIFIED",
  CODEX_BROWSER_SURFACE_BROWSER_SETTINGS_PAGE:
    "CODEX_BROWSER_SURFACE_BROWSER_SETTINGS_PAGE",
  CODEX_BROWSER_SURFACE_IN_APP_BROWSER_OVERFLOW_MENU:
    "CODEX_BROWSER_SURFACE_IN_APP_BROWSER_OVERFLOW_MENU",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexBrowserSurfaceName =
  (typeof CodexBrowserSurface)[keyof typeof CodexBrowserSurface];

/**
 * Bundle `NQn` / export `I6` — analytics event type descriptor for
 * CodexBrowserSurfaceAction product events.
 */
export const CodexBrowserSurfaceActionAnalyticsType = {
  $type: "protobuf_analytics_events.v1.CodexBrowserSurfaceAction",
} as const;

/** Bundle `PQn` / export `R6` — ESM init retained as no-op. */
export function ensureBrowserSurfaceEnumsInit(): void {}
