// Restored from ref/webview/assets/workbook-C49Dgk1_.js
// Stage-3 wave-79: deck-kinds mutable slots (legacy Binding1738–1748 / TRe…KRe).

export let workbookBinding1738: any;
export let TRe: any;
export let ERe: any;
export let DRe: any;
export let ORe: any;
export let kRe: any;
export let ARe: any;
export let workbookBinding1739: any;
export let jRe: any;
export let workbookBinding1740: any;
export let MRe: any;
export let NRe: any;
export let PRe: any;
export let FRe: any;
export let workbookBinding1741: any;
export let workbookBinding1742: any;
export let IRe: any;
export let LRe: any;
export let RRe: any;
export let zRe: any;
export let BRe: any;
export let VRe: any;
export let HRe: any;
export let URe: any;
export let WRe: any;
export let workbookBinding1743: any;
export let workbookBinding1744: any;
export let GRe: any;
export let workbookBinding1745: any;
export let workbookBinding1746: any;
export let KRe: any;
export let workbookBinding1747: any;
export let workbookBinding1748: any;
