// Restored from ref/webview/assets/local-environment-editor-9PiWGb5h.js
// Wave FZ — full polished body from `local-environment-editor-9PiWGb5h/auto-polished.tsx` with companion import rewrite.
// Soft-deferred host replaced; NOT app-initial extractFn / promote / producer barrel.
// Residual companion stubs: 20 (verified 61/80).
// Careful split 1/3
/* split-lane-import-depth:1 */

import { SUPPORTED_NODE_PLATFORMS } from "../../config/supported-node-platforms";
import { appServices } from "../../desktop/desktop-services";
import { buildVscodeQueryKey } from "../vscode-query-key";
import { echo } from "./part-1-a";

async function localEnvironmentEditorY(jasper, kelp, lotus, mint) {
  let nova = [
    ...Array.from(new Set(lotus)).flatMap((item) => [
      buildVscodeQueryKey("local-environment-config", {
        configPath: item,
        hostId: kelp,
      }),
      buildVscodeQueryKey("local-environment", {
        configPath: item,
        hostId: kelp,
      }),
    ]),
    ...(mint == null
      ? []
      : [
          buildVscodeQueryKey("local-environments", {
            hostId: kelp,
            workspaceRoot: mint,
          }),
        ]),
  ];
  await Promise.all(
    nova.map((item) =>
      jasper.invalidateQueries({
        queryKey: item,
      }),
    ),
  );
}
function gamma({
  version,
  name,
  setupScript,
  setupPlatformScripts,
  cleanupScript,
  cleanupPlatformScripts,
  actions,
}) {
  let yarn = actions.flatMap((item) => {
      let acorn = item.name.trim(),
        bloom = item.command.trim();
      return acorn.length === 0 || bloom.length === 0
        ? []
        : [
            {
              ...item,
              command: bloom,
              name: acorn,
            },
          ];
    }),
    zephyr = [];
  zephyr.push("# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY");
  zephyr.push(`version = ${version}`);
  zephyr.push(`name = ${indigo(name.trim())}`);
  harbor(zephyr, "setup", setupScript, setupPlatformScripts);
  harbor(zephyr, "cleanup", cleanupScript, cleanupPlatformScripts);
  yarn.length > 0 && zephyr.push("");
  for (let coral of yarn) {
    zephyr.push("[[actions]]");
    zephyr.push(`name = ${indigo(coral.name)}`);
    coral.icon && zephyr.push(`icon = ${indigo(coral.icon)}`);
    zephyr.push(`command = ${indigo(coral.command)}`);
    coral.platform && zephyr.push(`platform = ${indigo(coral.platform)}`);
    zephyr.push("");
  }
  return `${zephyr.join("\n").trimEnd()}\n`;
}
function harbor(drift, eagle, frost, glide) {
  let honey = SUPPORTED_NODE_PLATFORMS.flatMap((item) => {
    let iris = glide[item];
    return iris == null || iris.length === 0
      ? []
      : [
          {
            platform: item,
            script: iris,
          },
        ];
  });
  if (
    ((eagle === "setup" || frost.length > 0 || honey.length > 0) &&
      (drift.push(""),
      drift.push(`[${eagle}]`),
      drift.push(`script = ${indigo(frost)}`)),
    honey.length !== 0)
  ) {
    drift.push("");
    for (let [jewel, knoll] of honey.entries()) {
      drift.push(`[${eagle}.${knoll.platform}]`);
      drift.push(`script = ${indigo(knoll.script)}`);
      jewel < honey.length - 1 && drift.push("");
    }
  }
}
function indigo(lunar) {
  let moss = lunar.replace(/\r\n?/g, "\n");
  return moss.includes("\n")
    ? moss.includes("'''")
      ? `"""\n${moss.replace(/\\/g, "\\\\").replace(/"""/g, '\\"""')}"""`
      : `'''\n${moss}'''`
    : JSON.stringify(moss);
}
async function onyx({
  configPath,
  expectedRevision,
  hostId,
  queryClient,
  raw,
  selectEnvironment,
  workspaceRoot,
}) {
  let north = appServices.localEnvironments;
  if (north == null)
    throw Error("Local environments are not supported by this host.");
  let orbit = await north.saveConfig({
      configPath,
      expectedRevision,
      hostId,
      raw,
    }),
    pine = orbit.configPath,
    quest = localEnvironmentEditorY(
      queryClient,
      hostId,
      [configPath, pine],
      workspaceRoot,
    );
  return orbit.type === "conflict"
    ? {
        type: "conflict",
      }
    : (await quest,
      {
        configPath: pine,
        type:
          (await selectEnvironment?.(pine)) === false
            ? "selection-failed"
            : "success",
      });
}
async function localEnvironmentEditorC({
  configPath,
  draft,
  expectedRevision,
  hostId,
  queryClient,
  selectEnvironment,
  version,
  workspaceRoot,
}) {
  let ridge = echo(draft.name, draft.actions);
  return ridge.missingName || ridge.incompleteActionIds.length > 0
    ? {
        type: "invalid",
      }
    : onyx({
        configPath,
        expectedRevision,
        hostId,
        queryClient,
        raw: gamma({
          version,
          ...draft,
        }),
        selectEnvironment,
        workspaceRoot,
      });
}
async function pearl({
  codexWorktree,
  configPath,
  gitRoot,
  selectForWorkspace,
  selectForWorktree,
}) {
  return codexWorktree
    ? gitRoot == null
      ? false
      : selectForWorktree(gitRoot, configPath)
    : (selectForWorkspace(configPath), true);
}
