// Restored from ref/webview/assets/document-BMnWVkrx.js
// DOCX document protobuf PascalCase type re-export surface (typed boundary facade).
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 24 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const Artifact: any;
export declare const ArtifactType: any;
export declare const ColumnLayout: any;
export declare const Comment: any;
export declare const CommentReference: any;
export declare const Document: any;
export declare const DocumentGrid: any;
export declare const DocumentSection: any;
export declare const DocumentSettings: any;
export declare const EmbeddedFont: any;
export declare const EmbeddedFontType: any;
export declare const Endnote: any;
export declare const FontDefinition: any;
export declare const Footnote: any;
export declare const HeaderFooterContent: any;
export declare const NoteProperties: any;
export declare const NumberingDefinition: any;
export declare const NumberingLevel: any;
export declare const PageMargin: any;
export declare const PageSetup: any;
export declare const ParagraphNumbering: any;
export declare const Playground: any;
export declare const SectionBreakType: any;
export declare const protobufPackage: any;
