// Restored from ref/webview/assets/esm-B1fsB5y-.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 13 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const a: any;
export declare const c: any;
export declare const d: any;
export declare const f: any;
export declare const i: any;
export declare const l: any;
export declare const n: any;
export declare const o: any;
export declare const p: any;
export declare const r: any;
export declare const s: any;
export declare const t: any;
export declare const u: any;
