// Restored from ref/webview/assets/lodash-hNqvBNwd.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 43 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const A: any;
export declare const B: any;
export declare const C: any;
export declare const D: any;
export declare const E: any;
export declare const F: any;
export declare const H: any;
export declare const I: any;
export declare const L: any;
export declare const M: any;
export declare const N: any;
export declare const O: any;
export declare const P: any;
export declare const R: any;
export declare const S: any;
export declare const T: any;
export declare const U: any;
export declare const V: any;
export declare const _: any;
export declare const a: any;
export declare const b: any;
export declare const c: any;
export declare const d: any;
export declare const f: any;
export declare const g: any;
export declare const h: any;
export declare const i: any;
export declare const j: any;
export declare const k: any;
export declare const l: any;
export declare const m: any;
export declare const n: any;
export declare const o: any;
export declare const p: any;
export declare const r: any;
export declare const s: any;
export declare const t: any;
export declare const u: any;
export declare const v: any;
export declare const w: any;
export declare const x: any;
export declare const y: any;
export declare const z: any;
