// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `NZn` / export `J6`.

export const ChatgptTrustedContactEnrollmentStep = {
  CHATGPT_TRUSTED_CONTACT_ENROLLMENT_STEP_UNSPECIFIED:
    "CHATGPT_TRUSTED_CONTACT_ENROLLMENT_STEP_UNSPECIFIED",
  CHATGPT_TRUSTED_CONTACT_ENROLLMENT_STEP_INTRO:
    "CHATGPT_TRUSTED_CONTACT_ENROLLMENT_STEP_INTRO",
  CHATGPT_TRUSTED_CONTACT_ENROLLMENT_STEP_CONTACT_FORM:
    "CHATGPT_TRUSTED_CONTACT_ENROLLMENT_STEP_CONTACT_FORM",
  CHATGPT_TRUSTED_CONTACT_ENROLLMENT_STEP_PERSONAL_NOTE:
    "CHATGPT_TRUSTED_CONTACT_ENROLLMENT_STEP_PERSONAL_NOTE",
  CHATGPT_TRUSTED_CONTACT_ENROLLMENT_STEP_CONFIRMATION:
    "CHATGPT_TRUSTED_CONTACT_ENROLLMENT_STEP_CONFIRMATION",
  CHATGPT_TRUSTED_CONTACT_ENROLLMENT_STEP_NO_THANKS:
    "CHATGPT_TRUSTED_CONTACT_ENROLLMENT_STEP_NO_THANKS",
  CHATGPT_TRUSTED_CONTACT_ENROLLMENT_STEP_CONTACT_UNAVAILABLE:
    "CHATGPT_TRUSTED_CONTACT_ENROLLMENT_STEP_CONTACT_UNAVAILABLE",
  CHATGPT_TRUSTED_CONTACT_ENROLLMENT_STEP_ADD_NEW_CONTACT:
    "CHATGPT_TRUSTED_CONTACT_ENROLLMENT_STEP_ADD_NEW_CONTACT",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type ChatgptTrustedContactEnrollmentStep =
  (typeof ChatgptTrustedContactEnrollmentStep)[keyof typeof ChatgptTrustedContactEnrollmentStep];
