// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `vZn` / export `i8`.

export const ChatgptSafetyLinkType = {
  CHATGPT_SAFETY_LINK_TYPE_UNSPECIFIED: "CHATGPT_SAFETY_LINK_TYPE_UNSPECIFIED",
  CHATGPT_SAFETY_LINK_TYPE_TERMINAL_BLOCK_TRUSTED_ACCESS:
    "CHATGPT_SAFETY_LINK_TYPE_TERMINAL_BLOCK_TRUSTED_ACCESS",
  CHATGPT_SAFETY_LINK_TYPE_SAFETY_REVIEW_FASTER_MODEL:
    "CHATGPT_SAFETY_LINK_TYPE_SAFETY_REVIEW_FASTER_MODEL",
  CHATGPT_SAFETY_LINK_TYPE_SAFETY_REVIEW_LEARN_MORE:
    "CHATGPT_SAFETY_LINK_TYPE_SAFETY_REVIEW_LEARN_MORE",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type ChatgptSafetyLinkType =
  (typeof ChatgptSafetyLinkType)[keyof typeof ChatgptSafetyLinkType];
