// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `MZn` / export `X6`.

export const ChatgptTrustedContactEntryPoint = {
  CHATGPT_TRUSTED_CONTACT_ENTRY_POINT_UNSPECIFIED:
    "CHATGPT_TRUSTED_CONTACT_ENTRY_POINT_UNSPECIFIED",
  CHATGPT_TRUSTED_CONTACT_ENTRY_POINT_IN_CHAT_DISCLAIMER:
    "CHATGPT_TRUSTED_CONTACT_ENTRY_POINT_IN_CHAT_DISCLAIMER",
  CHATGPT_TRUSTED_CONTACT_ENTRY_POINT_SETTINGS:
    "CHATGPT_TRUSTED_CONTACT_ENTRY_POINT_SETTINGS",
  CHATGPT_TRUSTED_CONTACT_ENTRY_POINT_PUBLIC_ACCEPT_LINK:
    "CHATGPT_TRUSTED_CONTACT_ENTRY_POINT_PUBLIC_ACCEPT_LINK",
  CHATGPT_TRUSTED_CONTACT_ENTRY_POINT_PUBLIC_DECLINE_LINK:
    "CHATGPT_TRUSTED_CONTACT_ENTRY_POINT_PUBLIC_DECLINE_LINK",
  CHATGPT_TRUSTED_CONTACT_ENTRY_POINT_NOTIFICATION_WARNING:
    "CHATGPT_TRUSTED_CONTACT_ENTRY_POINT_NOTIFICATION_WARNING",
  CHATGPT_TRUSTED_CONTACT_ENTRY_POINT_ALERT_LINK:
    "CHATGPT_TRUSTED_CONTACT_ENTRY_POINT_ALERT_LINK",
  CHATGPT_TRUSTED_CONTACT_ENTRY_POINT_UNLINKED_LINK:
    "CHATGPT_TRUSTED_CONTACT_ENTRY_POINT_UNLINKED_LINK",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type ChatgptTrustedContactEntryPoint =
  (typeof ChatgptTrustedContactEntryPoint)[keyof typeof ChatgptTrustedContactEntryPoint];
