// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `tZt` / export `Jet` — protobuf analytics enum.

export const CodexProfileEditAction = {
  CODEX_PROFILE_EDIT_ACTION_UNSPECIFIED:
    "CODEX_PROFILE_EDIT_ACTION_UNSPECIFIED",
  CODEX_PROFILE_EDIT_ACTION_OPENED: "CODEX_PROFILE_EDIT_ACTION_OPENED",
  CODEX_PROFILE_EDIT_ACTION_SAVE_SUCCEEDED:
    "CODEX_PROFILE_EDIT_ACTION_SAVE_SUCCEEDED",
  CODEX_PROFILE_EDIT_ACTION_SAVE_FAILED:
    "CODEX_PROFILE_EDIT_ACTION_SAVE_FAILED",
  CODEX_PROFILE_EDIT_ACTION_MODAL_PHOTO_CHANGE_STARTED:
    "CODEX_PROFILE_EDIT_ACTION_MODAL_PHOTO_CHANGE_STARTED",
  CODEX_PROFILE_EDIT_ACTION_MODAL_PHOTO_CHANGE_IMAGE_SELECTED:
    "CODEX_PROFILE_EDIT_ACTION_MODAL_PHOTO_CHANGE_IMAGE_SELECTED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexProfileEditAction =
  (typeof CodexProfileEditAction)[keyof typeof CodexProfileEditAction];
