// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `FXt` / export `Ett` — protobuf analytics enum.

export const CodexRemoteSshConnectionEventSource = {
  CODEX_REMOTE_SSH_CONNECTION_EVENT_SOURCE_UNSPECIFIED:
    "CODEX_REMOTE_SSH_CONNECTION_EVENT_SOURCE_UNSPECIFIED",
  CODEX_REMOTE_SSH_CONNECTION_EVENT_SOURCE_SETTINGS:
    "CODEX_REMOTE_SSH_CONNECTION_EVENT_SOURCE_SETTINGS",
  CODEX_REMOTE_SSH_CONNECTION_EVENT_SOURCE_PROJECT_SETUP:
    "CODEX_REMOTE_SSH_CONNECTION_EVENT_SOURCE_PROJECT_SETUP",
  CODEX_REMOTE_SSH_CONNECTION_EVENT_SOURCE_CONNECTION_MANAGER:
    "CODEX_REMOTE_SSH_CONNECTION_EVENT_SOURCE_CONNECTION_MANAGER",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexRemoteSshConnectionEventSource =
  (typeof CodexRemoteSshConnectionEventSource)[keyof typeof CodexRemoteSshConnectionEventSource];
