// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `mys` / export `wb` — protobuf analytics enum.

export const CodexOnboardingWizardPhase = {
  CODEX_ONBOARDING_WIZARD_PHASE_UNSPECIFIED:
    "CODEX_ONBOARDING_WIZARD_PHASE_UNSPECIFIED",
  CODEX_ONBOARDING_WIZARD_PHASE_LAUNCH: "CODEX_ONBOARDING_WIZARD_PHASE_LAUNCH",
  CODEX_ONBOARDING_WIZARD_PHASE_ROLE_PICKER:
    "CODEX_ONBOARDING_WIZARD_PHASE_ROLE_PICKER",
  CODEX_ONBOARDING_WIZARD_PHASE_TASK_PICKER:
    "CODEX_ONBOARDING_WIZARD_PHASE_TASK_PICKER",
  CODEX_ONBOARDING_WIZARD_PHASE_CONTEXT_PICKER:
    "CODEX_ONBOARDING_WIZARD_PHASE_CONTEXT_PICKER",
  CODEX_ONBOARDING_WIZARD_PHASE_PLUGIN_INSTALL:
    "CODEX_ONBOARDING_WIZARD_PHASE_PLUGIN_INSTALL",
  CODEX_ONBOARDING_WIZARD_PHASE_FIRST_ARTIFACT:
    "CODEX_ONBOARDING_WIZARD_PHASE_FIRST_ARTIFACT",
  CODEX_ONBOARDING_WIZARD_PHASE_PLUGIN_PICKER:
    "CODEX_ONBOARDING_WIZARD_PHASE_PLUGIN_PICKER",
  CODEX_ONBOARDING_WIZARD_PHASE_COMPLETION:
    "CODEX_ONBOARDING_WIZARD_PHASE_COMPLETION",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexOnboardingWizardPhase =
  (typeof CodexOnboardingWizardPhase)[keyof typeof CodexOnboardingWizardPhase];
