// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `TT` / export `U6` — protobuf analytics enum.

export const CodexAutomationSource = {
  CODEX_AUTOMATION_SOURCE_UNSPECIFIED: "CODEX_AUTOMATION_SOURCE_UNSPECIFIED",
  CODEX_AUTOMATION_SOURCE_MANUAL_PAGE: "CODEX_AUTOMATION_SOURCE_MANUAL_PAGE",
  CODEX_AUTOMATION_SOURCE_SUGGESTED_CARD:
    "CODEX_AUTOMATION_SOURCE_SUGGESTED_CARD",
  CODEX_AUTOMATION_SOURCE_PENDING_WORKTREE:
    "CODEX_AUTOMATION_SOURCE_PENDING_WORKTREE",
  CODEX_AUTOMATION_SOURCE_PR_MERGE_HELPER:
    "CODEX_AUTOMATION_SOURCE_PR_MERGE_HELPER",
  CODEX_AUTOMATION_SOURCE_AGENT_TOOL: "CODEX_AUTOMATION_SOURCE_AGENT_TOOL",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexAutomationSource =
  (typeof CodexAutomationSource)[keyof typeof CodexAutomationSource];
