// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `LY` / export `IT` — protobuf analytics enum.

export const CodexBrowserSurfaceActionType = {
  CODEX_BROWSER_SURFACE_ACTION_TYPE_UNSPECIFIED:
    "CODEX_BROWSER_SURFACE_ACTION_TYPE_UNSPECIFIED",
  CODEX_BROWSER_SURFACE_ACTION_TYPE_CAPTURE_SCREENSHOT_SELECTED:
    "CODEX_BROWSER_SURFACE_ACTION_TYPE_CAPTURE_SCREENSHOT_SELECTED",
  CODEX_BROWSER_SURFACE_ACTION_TYPE_SHOW_DEVICE_TOOLBAR_SELECTED:
    "CODEX_BROWSER_SURFACE_ACTION_TYPE_SHOW_DEVICE_TOOLBAR_SELECTED",
  CODEX_BROWSER_SURFACE_ACTION_TYPE_PASSWORD_MANAGER_SELECTED:
    "CODEX_BROWSER_SURFACE_ACTION_TYPE_PASSWORD_MANAGER_SELECTED",
  CODEX_BROWSER_SURFACE_ACTION_TYPE_CONTACT_INFO_SELECTED:
    "CODEX_BROWSER_SURFACE_ACTION_TYPE_CONTACT_INFO_SELECTED",
  CODEX_BROWSER_SURFACE_ACTION_TYPE_DOWNLOADS_SELECTED:
    "CODEX_BROWSER_SURFACE_ACTION_TYPE_DOWNLOADS_SELECTED",
  CODEX_BROWSER_SURFACE_ACTION_TYPE_EXTENSIONS_SELECTED:
    "CODEX_BROWSER_SURFACE_ACTION_TYPE_EXTENSIONS_SELECTED",
  CODEX_BROWSER_SURFACE_ACTION_TYPE_HISTORY_SELECTED:
    "CODEX_BROWSER_SURFACE_ACTION_TYPE_HISTORY_SELECTED",
  CODEX_BROWSER_SURFACE_ACTION_TYPE_BROWSER_SETTINGS_SELECTED:
    "CODEX_BROWSER_SURFACE_ACTION_TYPE_BROWSER_SETTINGS_SELECTED",
  CODEX_BROWSER_SURFACE_ACTION_TYPE_SITE_SETTINGS_SELECTED:
    "CODEX_BROWSER_SURFACE_ACTION_TYPE_SITE_SETTINGS_SELECTED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexBrowserSurfaceActionType =
  (typeof CodexBrowserSurfaceActionType)[keyof typeof CodexBrowserSurfaceActionType];
