// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `Ab` / export `stt` — quick-chat lifecycle analytics action enum.

export const CodexQuickChatLifecycleAction = {
  CODEX_QUICK_CHAT_LIFECYCLE_ACTION_UNSPECIFIED:
    "CODEX_QUICK_CHAT_LIFECYCLE_ACTION_UNSPECIFIED",
  CODEX_QUICK_CHAT_LIFECYCLE_ACTION_OPENED:
    "CODEX_QUICK_CHAT_LIFECYCLE_ACTION_OPENED",
  CODEX_QUICK_CHAT_LIFECYCLE_ACTION_CLOSED:
    "CODEX_QUICK_CHAT_LIFECYCLE_ACTION_CLOSED",
  CODEX_QUICK_CHAT_LIFECYCLE_ACTION_CONVERSATION_STARTED:
    "CODEX_QUICK_CHAT_LIFECYCLE_ACTION_CONVERSATION_STARTED",
  CODEX_QUICK_CHAT_LIFECYCLE_ACTION_SUBMITTED:
    "CODEX_QUICK_CHAT_LIFECYCLE_ACTION_SUBMITTED",
  CODEX_QUICK_CHAT_LIFECYCLE_ACTION_SUBMIT_SUCCEEDED:
    "CODEX_QUICK_CHAT_LIFECYCLE_ACTION_SUBMIT_SUCCEEDED",
  CODEX_QUICK_CHAT_LIFECYCLE_ACTION_SUBMIT_FAILED:
    "CODEX_QUICK_CHAT_LIFECYCLE_ACTION_SUBMIT_FAILED",
  CODEX_QUICK_CHAT_LIFECYCLE_ACTION_ADD_TO_CODEX_CLICKED:
    "CODEX_QUICK_CHAT_LIFECYCLE_ACTION_ADD_TO_CODEX_CLICKED",
  CODEX_QUICK_CHAT_LIFECYCLE_ACTION_ADD_TO_CODEX_SUCCEEDED:
    "CODEX_QUICK_CHAT_LIFECYCLE_ACTION_ADD_TO_CODEX_SUCCEEDED",
  CODEX_QUICK_CHAT_LIFECYCLE_ACTION_ADD_TO_CODEX_FAILED:
    "CODEX_QUICK_CHAT_LIFECYCLE_ACTION_ADD_TO_CODEX_FAILED",
  CODEX_QUICK_CHAT_LIFECYCLE_ACTION_POPPED_OUT:
    "CODEX_QUICK_CHAT_LIFECYCLE_ACTION_POPPED_OUT",
  CODEX_QUICK_CHAT_LIFECYCLE_ACTION_DOCK_CHANGED:
    "CODEX_QUICK_CHAT_LIFECYCLE_ACTION_DOCK_CHANGED",
  CODEX_QUICK_CHAT_LIFECYCLE_ACTION_RESIZED:
    "CODEX_QUICK_CHAT_LIFECYCLE_ACTION_RESIZED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexQuickChatLifecycleAction =
  (typeof CodexQuickChatLifecycleAction)[keyof typeof CodexQuickChatLifecycleAction];
