// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `aZt` companion for exports `Kf`/`Bf`/`Gf`.

export const CodexConversationalOnboardingLifecycleAction = {
  CODEX_CONVERSATIONAL_ONBOARDING_LIFECYCLE_ACTION_UNSPECIFIED:
    "CODEX_CONVERSATIONAL_ONBOARDING_LIFECYCLE_ACTION_UNSPECIFIED",
  CODEX_CONVERSATIONAL_ONBOARDING_LIFECYCLE_ACTION_STARTED:
    "CODEX_CONVERSATIONAL_ONBOARDING_LIFECYCLE_ACTION_STARTED",
  CODEX_CONVERSATIONAL_ONBOARDING_LIFECYCLE_ACTION_COMPLETED:
    "CODEX_CONVERSATIONAL_ONBOARDING_LIFECYCLE_ACTION_COMPLETED",
  CODEX_CONVERSATIONAL_ONBOARDING_LIFECYCLE_ACTION_SKIPPED:
    "CODEX_CONVERSATIONAL_ONBOARDING_LIFECYCLE_ACTION_SKIPPED",
  CODEX_CONVERSATIONAL_ONBOARDING_LIFECYCLE_ACTION_FAILED:
    "CODEX_CONVERSATIONAL_ONBOARDING_LIFECYCLE_ACTION_FAILED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;
export type CodexConversationalOnboardingLifecycleAction =
  (typeof CodexConversationalOnboardingLifecycleAction)[keyof typeof CodexConversationalOnboardingLifecycleAction];
