// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `QXt` / export `ttt` — protobuf analytics enum.

export const CodexProfileShareAction = {
  CODEX_PROFILE_SHARE_ACTION_UNSPECIFIED:
    "CODEX_PROFILE_SHARE_ACTION_UNSPECIFIED",
  CODEX_PROFILE_SHARE_ACTION_SHARE_BUTTON_CLICKED:
    "CODEX_PROFILE_SHARE_ACTION_SHARE_BUTTON_CLICKED",
  CODEX_PROFILE_SHARE_ACTION_SOCIAL_SHARE_BUTTON_CLICKED:
    "CODEX_PROFILE_SHARE_ACTION_SOCIAL_SHARE_BUTTON_CLICKED",
  CODEX_PROFILE_SHARE_ACTION_SOCIAL_COMPOSER_BUTTON_CLICKED:
    "CODEX_PROFILE_SHARE_ACTION_SOCIAL_COMPOSER_BUTTON_CLICKED",
  CODEX_PROFILE_SHARE_ACTION_SAVE_BUTTON_CLICKED:
    "CODEX_PROFILE_SHARE_ACTION_SAVE_BUTTON_CLICKED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexProfileShareAction =
  (typeof CodexProfileShareAction)[keyof typeof CodexProfileShareAction];
