// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `JXt` / export `uet` — protobuf analytics enum.

export const CodexAvatarOverlaySource = {
  CODEX_AVATAR_OVERLAY_SOURCE_UNSPECIFIED:
    "CODEX_AVATAR_OVERLAY_SOURCE_UNSPECIFIED",
  CODEX_AVATAR_OVERLAY_SOURCE_SETTINGS: "CODEX_AVATAR_OVERLAY_SOURCE_SETTINGS",
  CODEX_AVATAR_OVERLAY_SOURCE_CONTEXT_MENU:
    "CODEX_AVATAR_OVERLAY_SOURCE_CONTEXT_MENU",
  CODEX_AVATAR_OVERLAY_SOURCE_MASCOT: "CODEX_AVATAR_OVERLAY_SOURCE_MASCOT",
  CODEX_AVATAR_OVERLAY_SOURCE_NOTIFICATION_BADGE:
    "CODEX_AVATAR_OVERLAY_SOURCE_NOTIFICATION_BADGE",
  CODEX_AVATAR_OVERLAY_SOURCE_NOTIFICATION_ROW:
    "CODEX_AVATAR_OVERLAY_SOURCE_NOTIFICATION_ROW",
  CODEX_AVATAR_OVERLAY_SOURCE_NOTIFICATION_REPLY:
    "CODEX_AVATAR_OVERLAY_SOURCE_NOTIFICATION_REPLY",
  CODEX_AVATAR_OVERLAY_SOURCE_WORK_MODE_START_SCREEN:
    "CODEX_AVATAR_OVERLAY_SOURCE_WORK_MODE_START_SCREEN",
  CODEX_AVATAR_OVERLAY_SOURCE_WORK_MODE_REASONING:
    "CODEX_AVATAR_OVERLAY_SOURCE_WORK_MODE_REASONING",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexAvatarOverlaySource =
  (typeof CodexAvatarOverlaySource)[keyof typeof CodexAvatarOverlaySource];
