// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `Cb` companion (local enum name in bundle) for export `Hf`.

export const CodexConversationalOnboardingFailureKind = {
  CODEX_CONVERSATIONAL_ONBOARDING_FAILURE_KIND_UNSPECIFIED:
    "CODEX_CONVERSATIONAL_ONBOARDING_FAILURE_KIND_UNSPECIFIED",
  CODEX_CONVERSATIONAL_ONBOARDING_FAILURE_KIND_HOST_SERVICE_UNAVAILABLE:
    "CODEX_CONVERSATIONAL_ONBOARDING_FAILURE_KIND_HOST_SERVICE_UNAVAILABLE",
  CODEX_CONVERSATIONAL_ONBOARDING_FAILURE_KIND_PLUGIN_UNAVAILABLE:
    "CODEX_CONVERSATIONAL_ONBOARDING_FAILURE_KIND_PLUGIN_UNAVAILABLE",
  CODEX_CONVERSATIONAL_ONBOARDING_FAILURE_KIND_REQUEST_FAILED:
    "CODEX_CONVERSATIONAL_ONBOARDING_FAILURE_KIND_REQUEST_FAILED",
  CODEX_CONVERSATIONAL_ONBOARDING_FAILURE_KIND_START_FAILED:
    "CODEX_CONVERSATIONAL_ONBOARDING_FAILURE_KIND_START_FAILED",
  CODEX_CONVERSATIONAL_ONBOARDING_FAILURE_KIND_COMPLETION_MISSING:
    "CODEX_CONVERSATIONAL_ONBOARDING_FAILURE_KIND_COMPLETION_MISSING",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;
export type CodexConversationalOnboardingFailureKind =
  (typeof CodexConversationalOnboardingFailureKind)[keyof typeof CodexConversationalOnboardingFailureKind];
