// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `$vs` / export `Eb` — protobuf analytics enum.

export const CodexReferralInviteModalAction = {
  CODEX_REFERRAL_INVITE_MODAL_ACTION_UNSPECIFIED:
    "CODEX_REFERRAL_INVITE_MODAL_ACTION_UNSPECIFIED",
  CODEX_REFERRAL_INVITE_MODAL_ACTION_SHOWN:
    "CODEX_REFERRAL_INVITE_MODAL_ACTION_SHOWN",
  CODEX_REFERRAL_INVITE_MODAL_ACTION_CLOSE_CLICKED:
    "CODEX_REFERRAL_INVITE_MODAL_ACTION_CLOSE_CLICKED",
  CODEX_REFERRAL_INVITE_MODAL_ACTION_SEND_CLICKED:
    "CODEX_REFERRAL_INVITE_MODAL_ACTION_SEND_CLICKED",
  CODEX_REFERRAL_INVITE_MODAL_ACTION_SEND_SUCCEEDED:
    "CODEX_REFERRAL_INVITE_MODAL_ACTION_SEND_SUCCEEDED",
  CODEX_REFERRAL_INVITE_MODAL_ACTION_BACKEND_ERROR:
    "CODEX_REFERRAL_INVITE_MODAL_ACTION_BACKEND_ERROR",
  CODEX_REFERRAL_INVITE_MODAL_ACTION_DONE_CLICKED:
    "CODEX_REFERRAL_INVITE_MODAL_ACTION_DONE_CLICKED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexReferralInviteModalAction =
  (typeof CodexReferralInviteModalAction)[keyof typeof CodexReferralInviteModalAction];
