// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `iZt` companion for `rlc` / export `qf`.

export const CodexConversationalOnboardingTaskType = {
  CODEX_CONVERSATIONAL_ONBOARDING_TASK_TYPE_UNSPECIFIED:
    "CODEX_CONVERSATIONAL_ONBOARDING_TASK_TYPE_UNSPECIFIED",
  CODEX_CONVERSATIONAL_ONBOARDING_TASK_TYPE_DESKTOP_NOTE:
    "CODEX_CONVERSATIONAL_ONBOARDING_TASK_TYPE_DESKTOP_NOTE",
  CODEX_CONVERSATIONAL_ONBOARDING_TASK_TYPE_CSV_CHART:
    "CODEX_CONVERSATIONAL_ONBOARDING_TASK_TYPE_CSV_CHART",
  CODEX_CONVERSATIONAL_ONBOARDING_TASK_TYPE_HOLD_NEXT_FREE_HOUR:
    "CODEX_CONVERSATIONAL_ONBOARDING_TASK_TYPE_HOLD_NEXT_FREE_HOUR",
  CODEX_CONVERSATIONAL_ONBOARDING_TASK_TYPE_SEND_MESSAGE_TO_SELF:
    "CODEX_CONVERSATIONAL_ONBOARDING_TASK_TYPE_SEND_MESSAGE_TO_SELF",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;
export type CodexConversationalOnboardingTaskType =
  (typeof CodexConversationalOnboardingTaskType)[keyof typeof CodexConversationalOnboardingTaskType];
