// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `jb` / export `ctt` — quick-chat analytics source enum.

export const CodexQuickChatSource = {
  CODEX_QUICK_CHAT_SOURCE_UNSPECIFIED: "CODEX_QUICK_CHAT_SOURCE_UNSPECIFIED",
  CODEX_QUICK_CHAT_SOURCE_COMMAND: "CODEX_QUICK_CHAT_SOURCE_COMMAND",
  CODEX_QUICK_CHAT_SOURCE_SIDEBAR: "CODEX_QUICK_CHAT_SOURCE_SIDEBAR",
  CODEX_QUICK_CHAT_SOURCE_SELECTED_TEXT:
    "CODEX_QUICK_CHAT_SOURCE_SELECTED_TEXT",
  CODEX_QUICK_CHAT_SOURCE_CONVERSATION_REFERENCE:
    "CODEX_QUICK_CHAT_SOURCE_CONVERSATION_REFERENCE",
  CODEX_QUICK_CHAT_SOURCE_FILE_PREVIEW: "CODEX_QUICK_CHAT_SOURCE_FILE_PREVIEW",
  CODEX_QUICK_CHAT_SOURCE_HEADER_NEW_CHAT:
    "CODEX_QUICK_CHAT_SOURCE_HEADER_NEW_CHAT",
  CODEX_QUICK_CHAT_SOURCE_HISTORY_NEW_CHAT:
    "CODEX_QUICK_CHAT_SOURCE_HISTORY_NEW_CHAT",
  CODEX_QUICK_CHAT_SOURCE_HISTORY_CONVERSATION:
    "CODEX_QUICK_CHAT_SOURCE_HISTORY_CONVERSATION",
  CODEX_QUICK_CHAT_SOURCE_EMPTY_STATE_CONVERSATION:
    "CODEX_QUICK_CHAT_SOURCE_EMPTY_STATE_CONVERSATION",
  CODEX_QUICK_CHAT_SOURCE_BACKDROP: "CODEX_QUICK_CHAT_SOURCE_BACKDROP",
  CODEX_QUICK_CHAT_SOURCE_CLOSE_BUTTON: "CODEX_QUICK_CHAT_SOURCE_CLOSE_BUTTON",
  CODEX_QUICK_CHAT_SOURCE_ESCAPE_KEY: "CODEX_QUICK_CHAT_SOURCE_ESCAPE_KEY",
  CODEX_QUICK_CHAT_SOURCE_ADD_TO_CODEX_BUTTON:
    "CODEX_QUICK_CHAT_SOURCE_ADD_TO_CODEX_BUTTON",
  CODEX_QUICK_CHAT_SOURCE_POPOUT_BUTTON:
    "CODEX_QUICK_CHAT_SOURCE_POPOUT_BUTTON",
  CODEX_QUICK_CHAT_SOURCE_DRAG: "CODEX_QUICK_CHAT_SOURCE_DRAG",
  CODEX_QUICK_CHAT_SOURCE_RESIZE_HANDLE:
    "CODEX_QUICK_CHAT_SOURCE_RESIZE_HANDLE",
  CODEX_QUICK_CHAT_SOURCE_COMPOSER: "CODEX_QUICK_CHAT_SOURCE_COMPOSER",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexQuickChatSource =
  (typeof CodexQuickChatSource)[keyof typeof CodexQuickChatSource];
