// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `Svs` / export `Nb` — protobuf analytics enum.

export const CodexInAppBrowserToolbarActionType = {
  CODEX_IN_APP_BROWSER_TOOLBAR_ACTION_TYPE_UNSPECIFIED:
    "CODEX_IN_APP_BROWSER_TOOLBAR_ACTION_TYPE_UNSPECIFIED",
  CODEX_IN_APP_BROWSER_TOOLBAR_ACTION_TYPE_CAPTURE_SCREENSHOT_CLICKED:
    "CODEX_IN_APP_BROWSER_TOOLBAR_ACTION_TYPE_CAPTURE_SCREENSHOT_CLICKED",
  CODEX_IN_APP_BROWSER_TOOLBAR_ACTION_TYPE_DEVICE_TOOLBAR_MODE_ENTERED:
    "CODEX_IN_APP_BROWSER_TOOLBAR_ACTION_TYPE_DEVICE_TOOLBAR_MODE_ENTERED",
  CODEX_IN_APP_BROWSER_TOOLBAR_ACTION_TYPE_DEVICE_TOOLBAR_DIMENSIONS_CHANGED:
    "CODEX_IN_APP_BROWSER_TOOLBAR_ACTION_TYPE_DEVICE_TOOLBAR_DIMENSIONS_CHANGED",
  CODEX_IN_APP_BROWSER_TOOLBAR_ACTION_TYPE_DEVICE_TOOLBAR_ROTATED:
    "CODEX_IN_APP_BROWSER_TOOLBAR_ACTION_TYPE_DEVICE_TOOLBAR_ROTATED",
  CODEX_IN_APP_BROWSER_TOOLBAR_ACTION_TYPE_OPENED_IN_EXTERNAL_BROWSER:
    "CODEX_IN_APP_BROWSER_TOOLBAR_ACTION_TYPE_OPENED_IN_EXTERNAL_BROWSER",
  CODEX_IN_APP_BROWSER_TOOLBAR_ACTION_TYPE_DEVICE_TOOLBAR_DIMENSIONS_INPUT_CHANGED:
    "CODEX_IN_APP_BROWSER_TOOLBAR_ACTION_TYPE_DEVICE_TOOLBAR_DIMENSIONS_INPUT_CHANGED",
  CODEX_IN_APP_BROWSER_TOOLBAR_ACTION_TYPE_DEVICE_TOOLBAR_DIMENSIONS_DRAG_CHANGED:
    "CODEX_IN_APP_BROWSER_TOOLBAR_ACTION_TYPE_DEVICE_TOOLBAR_DIMENSIONS_DRAG_CHANGED",
  CODEX_IN_APP_BROWSER_TOOLBAR_ACTION_TYPE_SITES_SETTINGS_CLICKED:
    "CODEX_IN_APP_BROWSER_TOOLBAR_ACTION_TYPE_SITES_SETTINGS_CLICKED",
  CODEX_IN_APP_BROWSER_TOOLBAR_ACTION_TYPE_SITES_SHARE_CLICKED:
    "CODEX_IN_APP_BROWSER_TOOLBAR_ACTION_TYPE_SITES_SHARE_CLICKED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexInAppBrowserToolbarActionType =
  (typeof CodexInAppBrowserToolbarActionType)[keyof typeof CodexInAppBrowserToolbarActionType];
