// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `kb` / export `Det` — protobuf analytics enum.

export const CodexNewChatSuggestionAction = {
  CODEX_NEW_CHAT_SUGGESTION_ACTION_UNSPECIFIED:
    "CODEX_NEW_CHAT_SUGGESTION_ACTION_UNSPECIFIED",
  CODEX_NEW_CHAT_SUGGESTION_ACTION_DISPLAYED:
    "CODEX_NEW_CHAT_SUGGESTION_ACTION_DISPLAYED",
  CODEX_NEW_CHAT_SUGGESTION_ACTION_CATEGORY_SELECTED:
    "CODEX_NEW_CHAT_SUGGESTION_ACTION_CATEGORY_SELECTED",
  CODEX_NEW_CHAT_SUGGESTION_ACTION_FOLLOW_UPS_DISPLAYED:
    "CODEX_NEW_CHAT_SUGGESTION_ACTION_FOLLOW_UPS_DISPLAYED",
  CODEX_NEW_CHAT_SUGGESTION_ACTION_FOLLOW_UP_SELECTED:
    "CODEX_NEW_CHAT_SUGGESTION_ACTION_FOLLOW_UP_SELECTED",
  CODEX_NEW_CHAT_SUGGESTION_ACTION_MORE_SUGGESTIONS_SELECTED:
    "CODEX_NEW_CHAT_SUGGESTION_ACTION_MORE_SUGGESTIONS_SELECTED",
  CODEX_NEW_CHAT_SUGGESTION_ACTION_DISMISSED:
    "CODEX_NEW_CHAT_SUGGESTION_ACTION_DISMISSED",
  CODEX_NEW_CHAT_SUGGESTION_ACTION_PLUGIN_INSTALLED:
    "CODEX_NEW_CHAT_SUGGESTION_ACTION_PLUGIN_INSTALLED",
  CODEX_NEW_CHAT_SUGGESTION_ACTION_REQUIRED_APP_CONNECT_STARTED:
    "CODEX_NEW_CHAT_SUGGESTION_ACTION_REQUIRED_APP_CONNECT_STARTED",
  CODEX_NEW_CHAT_SUGGESTION_ACTION_REQUIRED_APP_CONNECTED:
    "CODEX_NEW_CHAT_SUGGESTION_ACTION_REQUIRED_APP_CONNECTED",
  CODEX_NEW_CHAT_SUGGESTION_ACTION_APP_CONNECT_MODAL_OPENED:
    "CODEX_NEW_CHAT_SUGGESTION_ACTION_APP_CONNECT_MODAL_OPENED",
  CODEX_NEW_CHAT_SUGGESTION_ACTION_MESSAGE_SENT:
    "CODEX_NEW_CHAT_SUGGESTION_ACTION_MESSAGE_SENT",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexNewChatSuggestionAction =
  (typeof CodexNewChatSuggestionAction)[keyof typeof CodexNewChatSuggestionAction];
