// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `ET` / export `H6` — protobuf analytics enum.

export const CodexAutomationFailureReason = {
  CODEX_AUTOMATION_FAILURE_REASON_UNSPECIFIED:
    "CODEX_AUTOMATION_FAILURE_REASON_UNSPECIFIED",
  CODEX_AUTOMATION_FAILURE_REASON_HOST_ERROR:
    "CODEX_AUTOMATION_FAILURE_REASON_HOST_ERROR",
  CODEX_AUTOMATION_FAILURE_REASON_MISSING_AUTOMATION:
    "CODEX_AUTOMATION_FAILURE_REASON_MISSING_AUTOMATION",
  CODEX_AUTOMATION_FAILURE_REASON_INVALID_ID:
    "CODEX_AUTOMATION_FAILURE_REASON_INVALID_ID",
  CODEX_AUTOMATION_FAILURE_REASON_STORAGE_UNAVAILABLE:
    "CODEX_AUTOMATION_FAILURE_REASON_STORAGE_UNAVAILABLE",
  CODEX_AUTOMATION_FAILURE_REASON_STATE_CLEANUP_FAILED:
    "CODEX_AUTOMATION_FAILURE_REASON_STATE_CLEANUP_FAILED",
  CODEX_AUTOMATION_FAILURE_REASON_REMOVE_FAILED:
    "CODEX_AUTOMATION_FAILURE_REASON_REMOVE_FAILED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexAutomationFailureReason =
  (typeof CodexAutomationFailureReason)[keyof typeof CodexAutomationFailureReason];
