// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `pvs` / export `Pb` — protobuf analytics enum.

export const CodexRealtimeVoiceSessionEndReason = {
  CODEX_REALTIME_VOICE_SESSION_END_REASON_UNSPECIFIED:
    "CODEX_REALTIME_VOICE_SESSION_END_REASON_UNSPECIFIED",
  CODEX_REALTIME_VOICE_SESSION_END_REASON_USER_ENDED:
    "CODEX_REALTIME_VOICE_SESSION_END_REASON_USER_ENDED",
  CODEX_REALTIME_VOICE_SESSION_END_REASON_INACTIVITY:
    "CODEX_REALTIME_VOICE_SESSION_END_REASON_INACTIVITY",
  CODEX_REALTIME_VOICE_SESSION_END_REASON_APP_UNMOUNTED:
    "CODEX_REALTIME_VOICE_SESSION_END_REASON_APP_UNMOUNTED",
  CODEX_REALTIME_VOICE_SESSION_END_REASON_ERROR:
    "CODEX_REALTIME_VOICE_SESSION_END_REASON_ERROR",
  CODEX_REALTIME_VOICE_SESSION_END_REASON_SERVER_CLOSED:
    "CODEX_REALTIME_VOICE_SESSION_END_REASON_SERVER_CLOSED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexRealtimeVoiceSessionEndReason =
  (typeof CodexRealtimeVoiceSessionEndReason)[keyof typeof CodexRealtimeVoiceSessionEndReason];
