// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `lZt` companion for `nlc` / export `zf`.

export const CodexConversationalOnboardingAccessType = {
  CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_TYPE_UNSPECIFIED:
    "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_TYPE_UNSPECIFIED",
  CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_TYPE_DESKTOP:
    "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_TYPE_DESKTOP",
  CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_TYPE_CSV_PICKER:
    "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_TYPE_CSV_PICKER",
  CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_TYPE_CALENDAR_APP:
    "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_TYPE_CALENDAR_APP",
  CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_TYPE_MESSAGING_APP:
    "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_TYPE_MESSAGING_APP",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;
export type CodexConversationalOnboardingAccessType =
  (typeof CodexConversationalOnboardingAccessType)[keyof typeof CodexConversationalOnboardingAccessType];
