// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `CZt` / export `det`.

export const CodexChatgptHandoffLifecycleAction = {
  CODEX_CHATGPT_HANDOFF_LIFECYCLE_ACTION_UNSPECIFIED:
    "CODEX_CHATGPT_HANDOFF_LIFECYCLE_ACTION_UNSPECIFIED",
  CODEX_CHATGPT_HANDOFF_LIFECYCLE_ACTION_TOOL_CALLED:
    "CODEX_CHATGPT_HANDOFF_LIFECYCLE_ACTION_TOOL_CALLED",
  CODEX_CHATGPT_HANDOFF_LIFECYCLE_ACTION_ACCEPTED:
    "CODEX_CHATGPT_HANDOFF_LIFECYCLE_ACTION_ACCEPTED",
  CODEX_CHATGPT_HANDOFF_LIFECYCLE_ACTION_REJECTED:
    "CODEX_CHATGPT_HANDOFF_LIFECYCLE_ACTION_REJECTED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexChatgptHandoffLifecycleAction =
  (typeof CodexChatgptHandoffLifecycleAction)[keyof typeof CodexChatgptHandoffLifecycleAction];
