// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `nZt` / export `Zet` — protobuf analytics enum.

export const CodexProfileInlinePhotoChangeAction = {
  CODEX_PROFILE_INLINE_PHOTO_CHANGE_ACTION_UNSPECIFIED:
    "CODEX_PROFILE_INLINE_PHOTO_CHANGE_ACTION_UNSPECIFIED",
  CODEX_PROFILE_INLINE_PHOTO_CHANGE_ACTION_STARTED:
    "CODEX_PROFILE_INLINE_PHOTO_CHANGE_ACTION_STARTED",
  CODEX_PROFILE_INLINE_PHOTO_CHANGE_ACTION_IMAGE_SELECTED:
    "CODEX_PROFILE_INLINE_PHOTO_CHANGE_ACTION_IMAGE_SELECTED",
  CODEX_PROFILE_INLINE_PHOTO_CHANGE_ACTION_SUCCEEDED:
    "CODEX_PROFILE_INLINE_PHOTO_CHANGE_ACTION_SUCCEEDED",
  CODEX_PROFILE_INLINE_PHOTO_CHANGE_ACTION_FAILED:
    "CODEX_PROFILE_INLINE_PHOTO_CHANGE_ACTION_FAILED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexProfileInlinePhotoChangeAction =
  (typeof CodexProfileInlinePhotoChangeAction)[keyof typeof CodexProfileInlinePhotoChangeAction];
