// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `Yys` / export `xb` — protobuf analytics enum.

export const CodexPostLoginStatsigBootstrapFailureType = {
  CODEX_POST_LOGIN_STATSIG_BOOTSTRAP_FAILURE_TYPE_UNSPECIFIED:
    "CODEX_POST_LOGIN_STATSIG_BOOTSTRAP_FAILURE_TYPE_UNSPECIFIED",
  CODEX_POST_LOGIN_STATSIG_BOOTSTRAP_FAILURE_TYPE_REQUEST_FAILED:
    "CODEX_POST_LOGIN_STATSIG_BOOTSTRAP_FAILURE_TYPE_REQUEST_FAILED",
  CODEX_POST_LOGIN_STATSIG_BOOTSTRAP_FAILURE_TYPE_RESPONSE_INVALID:
    "CODEX_POST_LOGIN_STATSIG_BOOTSTRAP_FAILURE_TYPE_RESPONSE_INVALID",
  CODEX_POST_LOGIN_STATSIG_BOOTSTRAP_FAILURE_TYPE_CLIENT_INITIALIZATION_FAILED:
    "CODEX_POST_LOGIN_STATSIG_BOOTSTRAP_FAILURE_TYPE_CLIENT_INITIALIZATION_FAILED",
  CODEX_POST_LOGIN_STATSIG_BOOTSTRAP_FAILURE_TYPE_UNKNOWN:
    "CODEX_POST_LOGIN_STATSIG_BOOTSTRAP_FAILURE_TYPE_UNKNOWN",
  CODEX_POST_LOGIN_STATSIG_BOOTSTRAP_FAILURE_TYPE_AUTH_TOKEN_UNAVAILABLE:
    "CODEX_POST_LOGIN_STATSIG_BOOTSTRAP_FAILURE_TYPE_AUTH_TOKEN_UNAVAILABLE",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexPostLoginStatsigBootstrapFailureType =
  (typeof CodexPostLoginStatsigBootstrapFailureType)[keyof typeof CodexPostLoginStatsigBootstrapFailureType];
