// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `PZt` / export `dtt` — protobuf analytics enum.

export const CodexRealtimeVoiceSessionLifecycleAction = {
  CODEX_REALTIME_VOICE_SESSION_LIFECYCLE_ACTION_UNSPECIFIED:
    "CODEX_REALTIME_VOICE_SESSION_LIFECYCLE_ACTION_UNSPECIFIED",
  CODEX_REALTIME_VOICE_SESSION_LIFECYCLE_ACTION_START_REQUESTED:
    "CODEX_REALTIME_VOICE_SESSION_LIFECYCLE_ACTION_START_REQUESTED",
  CODEX_REALTIME_VOICE_SESSION_LIFECYCLE_ACTION_STARTED:
    "CODEX_REALTIME_VOICE_SESSION_LIFECYCLE_ACTION_STARTED",
  CODEX_REALTIME_VOICE_SESSION_LIFECYCLE_ACTION_START_FAILED:
    "CODEX_REALTIME_VOICE_SESSION_LIFECYCLE_ACTION_START_FAILED",
  CODEX_REALTIME_VOICE_SESSION_LIFECYCLE_ACTION_START_CANCELLED:
    "CODEX_REALTIME_VOICE_SESSION_LIFECYCLE_ACTION_START_CANCELLED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexRealtimeVoiceSessionLifecycleAction =
  (typeof CodexRealtimeVoiceSessionLifecycleAction)[keyof typeof CodexRealtimeVoiceSessionLifecycleAction];
