// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `IY` / export `LT` — protobuf analytics enum.

export const CodexPluginActionType = {
  CODEX_PLUGIN_ACTION_TYPE_UNSPECIFIED: "CODEX_PLUGIN_ACTION_TYPE_UNSPECIFIED",
  CODEX_PLUGIN_ACTION_TYPE_INSTALL: "CODEX_PLUGIN_ACTION_TYPE_INSTALL",
  CODEX_PLUGIN_ACTION_TYPE_ENABLE: "CODEX_PLUGIN_ACTION_TYPE_ENABLE",
  CODEX_PLUGIN_ACTION_TYPE_REMOVE: "CODEX_PLUGIN_ACTION_TYPE_REMOVE",
  CODEX_PLUGIN_ACTION_TYPE_OPEN_CONNECTOR_SETUP:
    "CODEX_PLUGIN_ACTION_TYPE_OPEN_CONNECTOR_SETUP",
  CODEX_PLUGIN_ACTION_TYPE_CONNECT_CONNECTOR:
    "CODEX_PLUGIN_ACTION_TYPE_CONNECT_CONNECTOR",
  CODEX_PLUGIN_ACTION_TYPE_DISABLE: "CODEX_PLUGIN_ACTION_TYPE_DISABLE",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexPluginActionType =
  (typeof CodexPluginActionType)[keyof typeof CodexPluginActionType];
