// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `cZt` companion for export `zf`.

export const CodexConversationalOnboardingAccessAction = {
  CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_ACTION_UNSPECIFIED:
    "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_ACTION_UNSPECIFIED",
  CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_ACTION_STARTED:
    "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_ACTION_STARTED",
  CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_ACTION_REQUESTED:
    "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_ACTION_REQUESTED",
  CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_ACTION_COMPLETED:
    "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_ACTION_COMPLETED",
  CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_ACTION_DENIED:
    "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_ACTION_DENIED",
  CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_ACTION_CANCELLED:
    "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_ACTION_CANCELLED",
  CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_ACTION_FAILED:
    "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_ACTION_FAILED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;
export type CodexConversationalOnboardingAccessAction =
  (typeof CodexConversationalOnboardingAccessAction)[keyof typeof CodexConversationalOnboardingAccessAction];
