// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `Bb` / export `ktt` — protobuf analytics enum.

export const CodexSafetyUxAction = {
  CODEX_SAFETY_UX_ACTION_UNSPECIFIED: "CODEX_SAFETY_UX_ACTION_UNSPECIFIED",
  CODEX_SAFETY_UX_ACTION_SHOWN: "CODEX_SAFETY_UX_ACTION_SHOWN",
  CODEX_SAFETY_UX_ACTION_LEARN_MORE_CLICKED:
    "CODEX_SAFETY_UX_ACTION_LEARN_MORE_CLICKED",
  CODEX_SAFETY_UX_ACTION_TRUSTED_ACCESS_CLICKED:
    "CODEX_SAFETY_UX_ACTION_TRUSTED_ACCESS_CLICKED",
  CODEX_SAFETY_UX_ACTION_FASTER_MODEL_CLICKED:
    "CODEX_SAFETY_UX_ACTION_FASTER_MODEL_CLICKED",
  CODEX_SAFETY_UX_ACTION_RETRY_CONFIRMED:
    "CODEX_SAFETY_UX_ACTION_RETRY_CONFIRMED",
  CODEX_SAFETY_UX_ACTION_RETRY_CANCELED:
    "CODEX_SAFETY_UX_ACTION_RETRY_CANCELED",
  CODEX_SAFETY_UX_ACTION_DISMISSED_FOR_TURN:
    "CODEX_SAFETY_UX_ACTION_DISMISSED_FOR_TURN",
  CODEX_SAFETY_UX_ACTION_DISMISSED_PERMANENTLY:
    "CODEX_SAFETY_UX_ACTION_DISMISSED_PERMANENTLY",
  CODEX_SAFETY_UX_ACTION_RETRY_DIALOG_OPENED:
    "CODEX_SAFETY_UX_ACTION_RETRY_DIALOG_OPENED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexSafetyUxAction =
  (typeof CodexSafetyUxAction)[keyof typeof CodexSafetyUxAction];
