// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `NXt` / export `Ctt` — protobuf analytics enum.

export const CodexRemoteSshConnectionAction = {
  CODEX_REMOTE_SSH_CONNECTION_ACTION_UNSPECIFIED:
    "CODEX_REMOTE_SSH_CONNECTION_ACTION_UNSPECIFIED",
  CODEX_REMOTE_SSH_CONNECTION_ACTION_REFRESH:
    "CODEX_REMOTE_SSH_CONNECTION_ACTION_REFRESH",
  CODEX_REMOTE_SSH_CONNECTION_ACTION_SAVE_CONNECTION:
    "CODEX_REMOTE_SSH_CONNECTION_ACTION_SAVE_CONNECTION",
  CODEX_REMOTE_SSH_CONNECTION_ACTION_CONNECT:
    "CODEX_REMOTE_SSH_CONNECTION_ACTION_CONNECT",
  CODEX_REMOTE_SSH_CONNECTION_ACTION_CREATE_REMOTE_PROJECT:
    "CODEX_REMOTE_SSH_CONNECTION_ACTION_CREATE_REMOTE_PROJECT",
  CODEX_REMOTE_SSH_CONNECTION_ACTION_STATE_CHANGED:
    "CODEX_REMOTE_SSH_CONNECTION_ACTION_STATE_CHANGED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexRemoteSshConnectionAction =
  (typeof CodexRemoteSshConnectionAction)[keyof typeof CodexRemoteSshConnectionAction];
