// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `Ib` / export `Uet` — protobuf analytics enum.

export const CodexPluginPageName = {
  CODEX_PLUGIN_PAGE_NAME_UNSPECIFIED: "CODEX_PLUGIN_PAGE_NAME_UNSPECIFIED",
  CODEX_PLUGIN_PAGE_NAME_DIRECTORY: "CODEX_PLUGIN_PAGE_NAME_DIRECTORY",
  CODEX_PLUGIN_PAGE_NAME_CATEGORY: "CODEX_PLUGIN_PAGE_NAME_CATEGORY",
  CODEX_PLUGIN_PAGE_NAME_WORKSPACE: "CODEX_PLUGIN_PAGE_NAME_WORKSPACE",
  CODEX_PLUGIN_PAGE_NAME_PERSONAL: "CODEX_PLUGIN_PAGE_NAME_PERSONAL",
  CODEX_PLUGIN_PAGE_NAME_SEARCH: "CODEX_PLUGIN_PAGE_NAME_SEARCH",
  CODEX_PLUGIN_PAGE_NAME_DETAILS: "CODEX_PLUGIN_PAGE_NAME_DETAILS",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexPluginPageName =
  (typeof CodexPluginPageName)[keyof typeof CodexPluginPageName];
