// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `GY` / export `kT` — protobuf analytics enum.

export const CodexAutomationReasoningEffort = {
  CODEX_AUTOMATION_REASONING_EFFORT_UNSPECIFIED:
    "CODEX_AUTOMATION_REASONING_EFFORT_UNSPECIFIED",
  CODEX_AUTOMATION_REASONING_EFFORT_NONE:
    "CODEX_AUTOMATION_REASONING_EFFORT_NONE",
  CODEX_AUTOMATION_REASONING_EFFORT_MINIMAL:
    "CODEX_AUTOMATION_REASONING_EFFORT_MINIMAL",
  CODEX_AUTOMATION_REASONING_EFFORT_LOW:
    "CODEX_AUTOMATION_REASONING_EFFORT_LOW",
  CODEX_AUTOMATION_REASONING_EFFORT_MEDIUM:
    "CODEX_AUTOMATION_REASONING_EFFORT_MEDIUM",
  CODEX_AUTOMATION_REASONING_EFFORT_HIGH:
    "CODEX_AUTOMATION_REASONING_EFFORT_HIGH",
  CODEX_AUTOMATION_REASONING_EFFORT_XHIGH:
    "CODEX_AUTOMATION_REASONING_EFFORT_XHIGH",
  CODEX_AUTOMATION_REASONING_EFFORT_MAX:
    "CODEX_AUTOMATION_REASONING_EFFORT_MAX",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexAutomationReasoningEffort =
  (typeof CodexAutomationReasoningEffort)[keyof typeof CodexAutomationReasoningEffort];
