// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `WZ` / export `Sb` — protobuf analytics enum.

export const CodexConversationalOnboardingExecutionAction = {
  CODEX_CONVERSATIONAL_ONBOARDING_EXECUTION_ACTION_UNSPECIFIED:
    "CODEX_CONVERSATIONAL_ONBOARDING_EXECUTION_ACTION_UNSPECIFIED",
  CODEX_CONVERSATIONAL_ONBOARDING_EXECUTION_ACTION_STARTED:
    "CODEX_CONVERSATIONAL_ONBOARDING_EXECUTION_ACTION_STARTED",
  CODEX_CONVERSATIONAL_ONBOARDING_EXECUTION_ACTION_COMPLETED:
    "CODEX_CONVERSATIONAL_ONBOARDING_EXECUTION_ACTION_COMPLETED",
  CODEX_CONVERSATIONAL_ONBOARDING_EXECUTION_ACTION_FAILED:
    "CODEX_CONVERSATIONAL_ONBOARDING_EXECUTION_ACTION_FAILED",
  CODEX_CONVERSATIONAL_ONBOARDING_EXECUTION_ACTION_CANCELLED:
    "CODEX_CONVERSATIONAL_ONBOARDING_EXECUTION_ACTION_CANCELLED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexConversationalOnboardingExecutionAction =
  (typeof CodexConversationalOnboardingExecutionAction)[keyof typeof CodexConversationalOnboardingExecutionAction];
