// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `qXt` / export `cet` — protobuf analytics enum.

export const CodexAvatarOverlayAction = {
  CODEX_AVATAR_OVERLAY_ACTION_UNSPECIFIED:
    "CODEX_AVATAR_OVERLAY_ACTION_UNSPECIFIED",
  CODEX_AVATAR_OVERLAY_ACTION_OPEN_REQUESTED:
    "CODEX_AVATAR_OVERLAY_ACTION_OPEN_REQUESTED",
  CODEX_AVATAR_OVERLAY_ACTION_CLOSE_REQUESTED:
    "CODEX_AVATAR_OVERLAY_ACTION_CLOSE_REQUESTED",
  CODEX_AVATAR_OVERLAY_ACTION_OPENED: "CODEX_AVATAR_OVERLAY_ACTION_OPENED",
  CODEX_AVATAR_OVERLAY_ACTION_PET_SELECTED:
    "CODEX_AVATAR_OVERLAY_ACTION_PET_SELECTED",
  CODEX_AVATAR_OVERLAY_ACTION_MASCOT_CLICKED:
    "CODEX_AVATAR_OVERLAY_ACTION_MASCOT_CLICKED",
  CODEX_AVATAR_OVERLAY_ACTION_DRAG_COMPLETED:
    "CODEX_AVATAR_OVERLAY_ACTION_DRAG_COMPLETED",
  CODEX_AVATAR_OVERLAY_ACTION_NOTIFICATION_TRAY_OPENED:
    "CODEX_AVATAR_OVERLAY_ACTION_NOTIFICATION_TRAY_OPENED",
  CODEX_AVATAR_OVERLAY_ACTION_NOTIFICATION_TRAY_CLOSED:
    "CODEX_AVATAR_OVERLAY_ACTION_NOTIFICATION_TRAY_CLOSED",
  CODEX_AVATAR_OVERLAY_ACTION_NOTIFICATION_OPENED:
    "CODEX_AVATAR_OVERLAY_ACTION_NOTIFICATION_OPENED",
  CODEX_AVATAR_OVERLAY_ACTION_NOTIFICATION_DISMISSED:
    "CODEX_AVATAR_OVERLAY_ACTION_NOTIFICATION_DISMISSED",
  CODEX_AVATAR_OVERLAY_ACTION_NOTIFICATION_REPLY_OPENED:
    "CODEX_AVATAR_OVERLAY_ACTION_NOTIFICATION_REPLY_OPENED",
  CODEX_AVATAR_OVERLAY_ACTION_NOTIFICATION_REPLY_SUBMITTED:
    "CODEX_AVATAR_OVERLAY_ACTION_NOTIFICATION_REPLY_SUBMITTED",
  CODEX_AVATAR_OVERLAY_ACTION_CLOSED: "CODEX_AVATAR_OVERLAY_ACTION_CLOSED",
  CODEX_AVATAR_OVERLAY_ACTION_CUSTOM_PET_CREATE_STARTED:
    "CODEX_AVATAR_OVERLAY_ACTION_CUSTOM_PET_CREATE_STARTED",
  CODEX_AVATAR_OVERLAY_ACTION_WORK_MODE_PET_SHOWN:
    "CODEX_AVATAR_OVERLAY_ACTION_WORK_MODE_PET_SHOWN",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexAvatarOverlayAction =
  (typeof CodexAvatarOverlayAction)[keyof typeof CodexAvatarOverlayAction];
