// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `VY` / export `NT` — protobuf analytics enum.

export const CodexBrowserProfileImportCookieStatus = {
  CODEX_BROWSER_PROFILE_IMPORT_COOKIE_STATUS_UNSPECIFIED:
    "CODEX_BROWSER_PROFILE_IMPORT_COOKIE_STATUS_UNSPECIFIED",
  CODEX_BROWSER_PROFILE_IMPORT_COOKIE_STATUS_MISSING:
    "CODEX_BROWSER_PROFILE_IMPORT_COOKIE_STATUS_MISSING",
  CODEX_BROWSER_PROFILE_IMPORT_COOKIE_STATUS_SUCCESS:
    "CODEX_BROWSER_PROFILE_IMPORT_COOKIE_STATUS_SUCCESS",
  CODEX_BROWSER_PROFILE_IMPORT_COOKIE_STATUS_FAILED_TO_COPY:
    "CODEX_BROWSER_PROFILE_IMPORT_COOKIE_STATUS_FAILED_TO_COPY",
  CODEX_BROWSER_PROFILE_IMPORT_COOKIE_STATUS_FAILED_TO_OPEN:
    "CODEX_BROWSER_PROFILE_IMPORT_COOKIE_STATUS_FAILED_TO_OPEN",
  CODEX_BROWSER_PROFILE_IMPORT_COOKIE_STATUS_FAILED_TO_READ:
    "CODEX_BROWSER_PROFILE_IMPORT_COOKIE_STATUS_FAILED_TO_READ",
  CODEX_BROWSER_PROFILE_IMPORT_COOKIE_STATUS_UNKNOWN:
    "CODEX_BROWSER_PROFILE_IMPORT_COOKIE_STATUS_UNKNOWN",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexBrowserProfileImportCookieStatus =
  (typeof CodexBrowserProfileImportCookieStatus)[keyof typeof CodexBrowserProfileImportCookieStatus];
