// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `_2o` / export `PT` — protobuf analytics enum.

export const CodexBrowserProfileImportPasswordStatus = {
  CODEX_BROWSER_PROFILE_IMPORT_PASSWORD_STATUS_UNSPECIFIED:
    "CODEX_BROWSER_PROFILE_IMPORT_PASSWORD_STATUS_UNSPECIFIED",
  CODEX_BROWSER_PROFILE_IMPORT_PASSWORD_STATUS_MISSING:
    "CODEX_BROWSER_PROFILE_IMPORT_PASSWORD_STATUS_MISSING",
  CODEX_BROWSER_PROFILE_IMPORT_PASSWORD_STATUS_SUCCESS:
    "CODEX_BROWSER_PROFILE_IMPORT_PASSWORD_STATUS_SUCCESS",
  CODEX_BROWSER_PROFILE_IMPORT_PASSWORD_STATUS_PARTIAL_SUCCESS:
    "CODEX_BROWSER_PROFILE_IMPORT_PASSWORD_STATUS_PARTIAL_SUCCESS",
  CODEX_BROWSER_PROFILE_IMPORT_PASSWORD_STATUS_FAILED_TO_COPY:
    "CODEX_BROWSER_PROFILE_IMPORT_PASSWORD_STATUS_FAILED_TO_COPY",
  CODEX_BROWSER_PROFILE_IMPORT_PASSWORD_STATUS_FAILED_TO_INITIALIZE:
    "CODEX_BROWSER_PROFILE_IMPORT_PASSWORD_STATUS_FAILED_TO_INITIALIZE",
  CODEX_BROWSER_PROFILE_IMPORT_PASSWORD_STATUS_FAILED_TO_READ:
    "CODEX_BROWSER_PROFILE_IMPORT_PASSWORD_STATUS_FAILED_TO_READ",
  CODEX_BROWSER_PROFILE_IMPORT_PASSWORD_STATUS_FAILED_TO_GET_TARGET_STORE:
    "CODEX_BROWSER_PROFILE_IMPORT_PASSWORD_STATUS_FAILED_TO_GET_TARGET_STORE",
  CODEX_BROWSER_PROFILE_IMPORT_PASSWORD_STATUS_FAILED_TO_READ_TARGET_STORE:
    "CODEX_BROWSER_PROFILE_IMPORT_PASSWORD_STATUS_FAILED_TO_READ_TARGET_STORE",
  CODEX_BROWSER_PROFILE_IMPORT_PASSWORD_STATUS_UNKNOWN:
    "CODEX_BROWSER_PROFILE_IMPORT_PASSWORD_STATUS_UNKNOWN",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexBrowserProfileImportPasswordStatus =
  (typeof CodexBrowserProfileImportPasswordStatus)[keyof typeof CodexBrowserProfileImportPasswordStatus];
