// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `GXt` — companion analytics enum (unexported; used by primary-runtime helpers).

export const CodexPrimaryRuntimeDependenciesResetStatus = {
  CODEX_PRIMARY_RUNTIME_DEPENDENCIES_RESET_STATUS_UNSPECIFIED:
    "CODEX_PRIMARY_RUNTIME_DEPENDENCIES_RESET_STATUS_UNSPECIFIED",
  CODEX_PRIMARY_RUNTIME_DEPENDENCIES_RESET_STATUS_INSTALLED:
    "CODEX_PRIMARY_RUNTIME_DEPENDENCIES_RESET_STATUS_INSTALLED",
  CODEX_PRIMARY_RUNTIME_DEPENDENCIES_RESET_STATUS_ALREADY_CURRENT:
    "CODEX_PRIMARY_RUNTIME_DEPENDENCIES_RESET_STATUS_ALREADY_CURRENT",
  CODEX_PRIMARY_RUNTIME_DEPENDENCIES_RESET_STATUS_FAILED:
    "CODEX_PRIMARY_RUNTIME_DEPENDENCIES_RESET_STATUS_FAILED",
  CODEX_PRIMARY_RUNTIME_DEPENDENCIES_RESET_STATUS_CANCELED:
    "CODEX_PRIMARY_RUNTIME_DEPENDENCIES_RESET_STATUS_CANCELED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexPrimaryRuntimeDependenciesResetStatus =
  (typeof CodexPrimaryRuntimeDependenciesResetStatus)[keyof typeof CodexPrimaryRuntimeDependenciesResetStatus];
