// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `Lb` companion for export `_z`.

export const CodexPluginPageReferrer = {
  CODEX_PLUGIN_PAGE_REFERRER_UNSPECIFIED:
    "CODEX_PLUGIN_PAGE_REFERRER_UNSPECIFIED",
  CODEX_PLUGIN_PAGE_REFERRER_DIRECTORY: "CODEX_PLUGIN_PAGE_REFERRER_DIRECTORY",
  CODEX_PLUGIN_PAGE_REFERRER_CATEGORY: "CODEX_PLUGIN_PAGE_REFERRER_CATEGORY",
  CODEX_PLUGIN_PAGE_REFERRER_WORKSPACE: "CODEX_PLUGIN_PAGE_REFERRER_WORKSPACE",
  CODEX_PLUGIN_PAGE_REFERRER_PERSONAL: "CODEX_PLUGIN_PAGE_REFERRER_PERSONAL",
  CODEX_PLUGIN_PAGE_REFERRER_SEARCH: "CODEX_PLUGIN_PAGE_REFERRER_SEARCH",
  CODEX_PLUGIN_PAGE_REFERRER_DEEP_LINK: "CODEX_PLUGIN_PAGE_REFERRER_DEEP_LINK",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexPluginPageReferrer =
  (typeof CodexPluginPageReferrer)[keyof typeof CodexPluginPageReferrer];
