// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `C$n` / export `D6` — protobuf analytics enum.

export const CodexMicroInputMonitoringPermissionState = {
  CODEX_MICRO_INPUT_MONITORING_PERMISSION_STATE_UNSPECIFIED:
    "CODEX_MICRO_INPUT_MONITORING_PERMISSION_STATE_UNSPECIFIED",
  CODEX_MICRO_INPUT_MONITORING_PERMISSION_STATE_GRANTED:
    "CODEX_MICRO_INPUT_MONITORING_PERMISSION_STATE_GRANTED",
  CODEX_MICRO_INPUT_MONITORING_PERMISSION_STATE_DENIED:
    "CODEX_MICRO_INPUT_MONITORING_PERMISSION_STATE_DENIED",
  CODEX_MICRO_INPUT_MONITORING_PERMISSION_STATE_UNAVAILABLE:
    "CODEX_MICRO_INPUT_MONITORING_PERMISSION_STATE_UNAVAILABLE",
  CODEX_MICRO_INPUT_MONITORING_PERMISSION_STATE_NOT_APPLICABLE:
    "CODEX_MICRO_INPUT_MONITORING_PERMISSION_STATE_NOT_APPLICABLE",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexMicroInputMonitoringPermissionState =
  (typeof CodexMicroInputMonitoringPermissionState)[keyof typeof CodexMicroInputMonitoringPermissionState];
