// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `rys` / export `Tb` — protobuf analytics enum.

export const CodexOnboardingWizardAction = {
  CODEX_ONBOARDING_WIZARD_ACTION_UNSPECIFIED:
    "CODEX_ONBOARDING_WIZARD_ACTION_UNSPECIFIED",
  CODEX_ONBOARDING_WIZARD_ACTION_COMPLETED:
    "CODEX_ONBOARDING_WIZARD_ACTION_COMPLETED",
  CODEX_ONBOARDING_WIZARD_ACTION_SKIPPED:
    "CODEX_ONBOARDING_WIZARD_ACTION_SKIPPED",
  CODEX_ONBOARDING_WIZARD_ACTION_DISMISSED:
    "CODEX_ONBOARDING_WIZARD_ACTION_DISMISSED",
  CODEX_ONBOARDING_WIZARD_ACTION_FAILED:
    "CODEX_ONBOARDING_WIZARD_ACTION_FAILED",
  CODEX_ONBOARDING_WIZARD_ACTION_VIEWED:
    "CODEX_ONBOARDING_WIZARD_ACTION_VIEWED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexOnboardingWizardAction =
  (typeof CodexOnboardingWizardAction)[keyof typeof CodexOnboardingWizardAction];
