// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Bundle `_b` / export `wtt` — protobuf analytics enum.

export const CodexRemoteSshConnectionErrorCategory = {
  CODEX_REMOTE_SSH_CONNECTION_ERROR_CATEGORY_UNSPECIFIED:
    "CODEX_REMOTE_SSH_CONNECTION_ERROR_CATEGORY_UNSPECIFIED",
  CODEX_REMOTE_SSH_CONNECTION_ERROR_CATEGORY_UNKNOWN:
    "CODEX_REMOTE_SSH_CONNECTION_ERROR_CATEGORY_UNKNOWN",
  CODEX_REMOTE_SSH_CONNECTION_ERROR_CATEGORY_CONNECTION_FAILED:
    "CODEX_REMOTE_SSH_CONNECTION_ERROR_CATEGORY_CONNECTION_FAILED",
  CODEX_REMOTE_SSH_CONNECTION_ERROR_CATEGORY_LOGIN_REQUIRED:
    "CODEX_REMOTE_SSH_CONNECTION_ERROR_CATEGORY_LOGIN_REQUIRED",
  CODEX_REMOTE_SSH_CONNECTION_ERROR_CATEGORY_UPDATE_REQUIRED:
    "CODEX_REMOTE_SSH_CONNECTION_ERROR_CATEGORY_UPDATE_REQUIRED",
  CODEX_REMOTE_SSH_CONNECTION_ERROR_CATEGORY_RESTART_REQUIRED:
    "CODEX_REMOTE_SSH_CONNECTION_ERROR_CATEGORY_RESTART_REQUIRED",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type CodexRemoteSshConnectionErrorCategory =
  (typeof CodexRemoteSshConnectionErrorCategory)[keyof typeof CodexRemoteSshConnectionErrorCategory];
