// Restored from ref/webview/assets/app-initial-C-fROkKo.js
// Materialized via extractFn(internal `E$n`) / export `j6`.

export type BindCODEXMICROCONNECTIONTRANSPORTUNSPECIFIEDPeers = {
  C$n: (...args: unknown[]) => unknown;
  S$n: (...args: unknown[]) => unknown;
  T$n: (...args: unknown[]) => unknown;
  b$n: (...args: unknown[]) => unknown;
  e: (...args: unknown[]) => unknown;
  w$n: (...args: unknown[]) => unknown;
  x$n: (...args: unknown[]) => unknown;
  y$n: (...args: unknown[]) => unknown;
};

let peers: BindCODEXMICROCONNECTIONTRANSPORTUNSPECIFIEDPeers | null = null;

/** Wire bindCODEXMICROCONNECTIONTRANSPORTUNSPECIFIED peers once companions land. */
export function setBindCODEXMICROCONNECTIONTRANSPORTUNSPECIFIEDPeers(next: BindCODEXMICROCONNECTIONTRANSPORTUNSPECIFIEDPeers): void {
  peers = next;
}

/**
 * Bundle export `j6` / internal `E$n`.
 */
export function bindCODEXMICROCONNECTIONTRANSPORTUNSPECIFIED() {
  if (peers == null) {
    throw new Error("bindCODEXMICROCONNECTIONTRANSPORTUNSPECIFIED peers are not configured");
  }

  return peers.e(() => {
    y$n = function (e) {
      return peers.e.CODEX_MICRO_CONNECTION_TRANSPORT_UNSPECIFIED = `CODEX_MICRO_CONNECTION_TRANSPORT_UNSPECIFIED`, peers.e.CODEX_MICRO_CONNECTION_TRANSPORT_USB = `CODEX_MICRO_CONNECTION_TRANSPORT_USB`, peers.e.CODEX_MICRO_CONNECTION_TRANSPORT_BLUETOOTH = `CODEX_MICRO_CONNECTION_TRANSPORT_BLUETOOTH`, peers.e.UNRECOGNIZED = `UNRECOGNIZED`, peers.e;
    }({}), b$n = function (e) {
      return peers.e.CODEX_MICRO_DEVICE_LIFECYCLE_STEP_TYPE_UNSPECIFIED = `CODEX_MICRO_DEVICE_LIFECYCLE_STEP_TYPE_UNSPECIFIED`, peers.e.CODEX_MICRO_DEVICE_LIFECYCLE_STEP_TYPE_FIRST_DETECTED = `CODEX_MICRO_DEVICE_LIFECYCLE_STEP_TYPE_FIRST_DETECTED`, peers.e.CODEX_MICRO_DEVICE_LIFECYCLE_STEP_TYPE_CONNECTED = `CODEX_MICRO_DEVICE_LIFECYCLE_STEP_TYPE_CONNECTED`, peers.e.CODEX_MICRO_DEVICE_LIFECYCLE_STEP_TYPE_CONNECTION_LOST = `CODEX_MICRO_DEVICE_LIFECYCLE_STEP_TYPE_CONNECTION_LOST`, peers.e.CODEX_MICRO_DEVICE_LIFECYCLE_STEP_TYPE_RECONNECTED = `CODEX_MICRO_DEVICE_LIFECYCLE_STEP_TYPE_RECONNECTED`, peers.e.CODEX_MICRO_DEVICE_LIFECYCLE_STEP_TYPE_CONNECTION_FAILED = `CODEX_MICRO_DEVICE_LIFECYCLE_STEP_TYPE_CONNECTION_FAILED`, peers.e.UNRECOGNIZED = `UNRECOGNIZED`, peers.e;
    }({}), x$n = function (e) {
      return peers.e.CODEX_MICRO_ONBOARDING_LIFECYCLE_STEP_TYPE_UNSPECIFIED = `CODEX_MICRO_ONBOARDING_LIFECYCLE_STEP_TYPE_UNSPECIFIED`, peers.e.CODEX_MICRO_ONBOARDING_LIFECYCLE_STEP_TYPE_SCREEN_SHOWN = `CODEX_MICRO_ONBOARDING_LIFECYCLE_STEP_TYPE_SCREEN_SHOWN`, peers.e.CODEX_MICRO_ONBOARDING_LIFECYCLE_STEP_TYPE_SCREEN_CONTINUED = `CODEX_MICRO_ONBOARDING_LIFECYCLE_STEP_TYPE_SCREEN_CONTINUED`, peers.e.CODEX_MICRO_ONBOARDING_LIFECYCLE_STEP_TYPE_FLOW_COMPLETED = `CODEX_MICRO_ONBOARDING_LIFECYCLE_STEP_TYPE_FLOW_COMPLETED`, peers.e.CODEX_MICRO_ONBOARDING_LIFECYCLE_STEP_TYPE_FLOW_DISMISSED = `CODEX_MICRO_ONBOARDING_LIFECYCLE_STEP_TYPE_FLOW_DISMISSED`, peers.e.CODEX_MICRO_ONBOARDING_LIFECYCLE_STEP_TYPE_SETTINGS_OPENED = `CODEX_MICRO_ONBOARDING_LIFECYCLE_STEP_TYPE_SETTINGS_OPENED`, peers.e.CODEX_MICRO_ONBOARDING_LIFECYCLE_STEP_TYPE_INPUT_MONITORING_SETTINGS_OPENED = `CODEX_MICRO_ONBOARDING_LIFECYCLE_STEP_TYPE_INPUT_MONITORING_SETTINGS_OPENED`, peers.e.CODEX_MICRO_ONBOARDING_LIFECYCLE_STEP_TYPE_INPUT_MONITORING_PERMISSION_GRANTED = `CODEX_MICRO_ONBOARDING_LIFECYCLE_STEP_TYPE_INPUT_MONITORING_PERMISSION_GRANTED`, peers.e.UNRECOGNIZED = `UNRECOGNIZED`, peers.e;
    }({}), S$n = function (e) {
      return peers.e.CODEX_MICRO_ONBOARDING_SCREEN_UNSPECIFIED = `CODEX_MICRO_ONBOARDING_SCREEN_UNSPECIFIED`, peers.e.CODEX_MICRO_ONBOARDING_SCREEN_WELCOME = `CODEX_MICRO_ONBOARDING_SCREEN_WELCOME`, peers.e.CODEX_MICRO_ONBOARDING_SCREEN_AGENT_KEYS = `CODEX_MICRO_ONBOARDING_SCREEN_AGENT_KEYS`, peers.e.CODEX_MICRO_ONBOARDING_SCREEN_COMMAND_KEYS = `CODEX_MICRO_ONBOARDING_SCREEN_COMMAND_KEYS`, peers.e.UNRECOGNIZED = `UNRECOGNIZED`, peers.e;
    }({}), C$n = function (e) {
      return peers.e.CODEX_MICRO_INPUT_MONITORING_PERMISSION_STATE_UNSPECIFIED = `CODEX_MICRO_INPUT_MONITORING_PERMISSION_STATE_UNSPECIFIED`, peers.e.CODEX_MICRO_INPUT_MONITORING_PERMISSION_STATE_GRANTED = `CODEX_MICRO_INPUT_MONITORING_PERMISSION_STATE_GRANTED`, peers.e.CODEX_MICRO_INPUT_MONITORING_PERMISSION_STATE_DENIED = `CODEX_MICRO_INPUT_MONITORING_PERMISSION_STATE_DENIED`, peers.e.CODEX_MICRO_INPUT_MONITORING_PERMISSION_STATE_UNAVAILABLE = `CODEX_MICRO_INPUT_MONITORING_PERMISSION_STATE_UNAVAILABLE`, peers.e.CODEX_MICRO_INPUT_MONITORING_PERMISSION_STATE_NOT_APPLICABLE = `CODEX_MICRO_INPUT_MONITORING_PERMISSION_STATE_NOT_APPLICABLE`, peers.e.UNRECOGNIZED = `UNRECOGNIZED`, peers.e;
    }({}), w$n = {
      $type: `protobuf_analytics_events.v1.CodexMicroDeviceLifecycleStep`
    }, T$n = {
      $type: `protobuf_analytics_events.v1.CodexMicroOnboardingLifecycleStep`
    };
  });
}
