// Restored from ref/webview/assets/pie-ZZUOXDRM-BXR-0O5M.js
// Mermaid Pie diagram entry (createPieServices lazy wrapper).
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 1 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const createPieServices: any;
