// Restored from ref/webview/assets/workbook-C49Dgk1_.js
// Stage-3 wave-70: table-styles mutable slots (legacy Nme…ahe).

export let workbookBinding688: any;
export let Ame: any;
export let jme: any;
export let Mme: any;
export let Pme: any;
export let Fme: any;
export let Ime: any;
export let Lme: any;
export let Rme: any;
export let zme: any;
export let Bme: any;
export let Vme: any;
export let Hme: any;
export let workbookBinding689: any;
export let workbookBinding690: any;
export let _w: any;
export let Qme: any;
export let $me: any;
export let ehe: any;
export let workbookBinding691: any;
export let workbookBinding692: any;
export let workbookBinding693: any;
export let workbookBinding694: any;
export let workbookBinding695: any;
export let workbookBinding696: any;
export let workbookBinding697: any;
export let the: any;
export let nhe: any;
export let rhe: any;
export let ihe: any;
export let workbookBinding698: any;
export let workbookBinding699: any;
