// Restored from ref/webview/assets/workbook-C49Dgk1_.js
// Stage-3 wave-1: presentation/chart protobuf ↔ camelCase name bridges.

import { ShapeGeometry } from "../shape-geometry";

export const shapeGeometryNameToProto = {
  line: ShapeGeometry.SHAPE_GEOMETRY_LINE,
  lineInv: ShapeGeometry.SHAPE_GEOMETRY_LINE_INV,
  triangle: ShapeGeometry.SHAPE_GEOMETRY_TRIANGLE,
  rtTriangle: ShapeGeometry.SHAPE_GEOMETRY_RT_TRIANGLE,
  rect: ShapeGeometry.SHAPE_GEOMETRY_RECT,
  diamond: ShapeGeometry.SHAPE_GEOMETRY_DIAMOND,
  parallelogram: ShapeGeometry.SHAPE_GEOMETRY_PARALLELOGRAM,
  trapezoid: ShapeGeometry.SHAPE_GEOMETRY_TRAPEZOID,
  nonIsoscelesTrapezoid: ShapeGeometry.SHAPE_GEOMETRY_NON_ISOSCELES_TRAPEZOID,
  pentagon: ShapeGeometry.SHAPE_GEOMETRY_PENTAGON,
  hexagon: ShapeGeometry.SHAPE_GEOMETRY_HEXAGON,
  heptagon: ShapeGeometry.SHAPE_GEOMETRY_HEPTAGON,
  octagon: ShapeGeometry.SHAPE_GEOMETRY_OCTAGON,
  decagon: ShapeGeometry.SHAPE_GEOMETRY_DECAGON,
  dodecagon: ShapeGeometry.SHAPE_GEOMETRY_DODECAGON,
  star4: ShapeGeometry.SHAPE_GEOMETRY_STAR4,
  star5: ShapeGeometry.SHAPE_GEOMETRY_STAR5,
  star6: ShapeGeometry.SHAPE_GEOMETRY_STAR6,
  star7: ShapeGeometry.SHAPE_GEOMETRY_STAR7,
  star8: ShapeGeometry.SHAPE_GEOMETRY_STAR8,
  star10: ShapeGeometry.SHAPE_GEOMETRY_STAR10,
  star12: ShapeGeometry.SHAPE_GEOMETRY_STAR12,
  star16: ShapeGeometry.SHAPE_GEOMETRY_STAR16,
  star24: ShapeGeometry.SHAPE_GEOMETRY_STAR24,
  star32: ShapeGeometry.SHAPE_GEOMETRY_STAR32,
  roundRect: ShapeGeometry.SHAPE_GEOMETRY_ROUND_RECT,
  round1Rect: ShapeGeometry.SHAPE_GEOMETRY_ROUND1_RECT,
  round2SameRect: ShapeGeometry.SHAPE_GEOMETRY_ROUND2_SAME_RECT,
  round2DiagRect: ShapeGeometry.SHAPE_GEOMETRY_ROUND2_DIAG_RECT,
  snipRoundRect: ShapeGeometry.SHAPE_GEOMETRY_SNIP_ROUND_RECT,
  snip1Rect: ShapeGeometry.SHAPE_GEOMETRY_SNIP1_RECT,
  snip2SameRect: ShapeGeometry.SHAPE_GEOMETRY_SNIP2_SAME_RECT,
  snip2DiagRect: ShapeGeometry.SHAPE_GEOMETRY_SNIP2_DIAG_RECT,
  plaque: ShapeGeometry.SHAPE_GEOMETRY_PLAQUE,
  ellipse: ShapeGeometry.SHAPE_GEOMETRY_ELLIPSE,
  teardrop: ShapeGeometry.SHAPE_GEOMETRY_TEARDROP,
  homePlate: ShapeGeometry.SHAPE_GEOMETRY_HOME_PLATE,
  chevron: ShapeGeometry.SHAPE_GEOMETRY_CHEVRON,
  pieWedge: ShapeGeometry.SHAPE_GEOMETRY_PIE_WEDGE,
  pie: ShapeGeometry.SHAPE_GEOMETRY_PIE,
  blockArc: ShapeGeometry.SHAPE_GEOMETRY_BLOCK_ARC,
  donut: ShapeGeometry.SHAPE_GEOMETRY_DONUT,
  noSmoking: ShapeGeometry.SHAPE_GEOMETRY_NO_SMOKING,
  rightArrow: ShapeGeometry.SHAPE_GEOMETRY_RIGHT_ARROW,
  leftArrow: ShapeGeometry.SHAPE_GEOMETRY_LEFT_ARROW,
  upArrow: ShapeGeometry.SHAPE_GEOMETRY_UP_ARROW,
  downArrow: ShapeGeometry.SHAPE_GEOMETRY_DOWN_ARROW,
  stripedRightArrow: ShapeGeometry.SHAPE_GEOMETRY_STRIPED_RIGHT_ARROW,
  notchedRightArrow: ShapeGeometry.SHAPE_GEOMETRY_NOTCHED_RIGHT_ARROW,
  bentUpArrow: ShapeGeometry.SHAPE_GEOMETRY_BENT_UP_ARROW,
  leftRightArrow: ShapeGeometry.SHAPE_GEOMETRY_LEFT_RIGHT_ARROW,
  upDownArrow: ShapeGeometry.SHAPE_GEOMETRY_UP_DOWN_ARROW,
  leftUpArrow: ShapeGeometry.SHAPE_GEOMETRY_LEFT_UP_ARROW,
  leftRightUpArrow: ShapeGeometry.SHAPE_GEOMETRY_LEFT_RIGHT_UP_ARROW,
  quadArrow: ShapeGeometry.SHAPE_GEOMETRY_QUAD_ARROW,
  leftArrowCallout: ShapeGeometry.SHAPE_GEOMETRY_LEFT_ARROW_CALLOUT,
  rightArrowCallout: ShapeGeometry.SHAPE_GEOMETRY_RIGHT_ARROW_CALLOUT,
  upArrowCallout: ShapeGeometry.SHAPE_GEOMETRY_UP_ARROW_CALLOUT,
  downArrowCallout: ShapeGeometry.SHAPE_GEOMETRY_DOWN_ARROW_CALLOUT,
  leftRightArrowCallout: ShapeGeometry.SHAPE_GEOMETRY_LEFT_RIGHT_ARROW_CALLOUT,
  upDownArrowCallout: ShapeGeometry.SHAPE_GEOMETRY_UP_DOWN_ARROW_CALLOUT,
  quadArrowCallout: ShapeGeometry.SHAPE_GEOMETRY_QUAD_ARROW_CALLOUT,
  bentArrow: ShapeGeometry.SHAPE_GEOMETRY_BENT_ARROW,
  uturnArrow: ShapeGeometry.SHAPE_GEOMETRY_UTURN_ARROW,
  circularArrow: ShapeGeometry.SHAPE_GEOMETRY_CIRCULAR_ARROW,
  leftCircularArrow: ShapeGeometry.SHAPE_GEOMETRY_LEFT_CIRCULAR_ARROW,
  leftRightCircularArrow:
    ShapeGeometry.SHAPE_GEOMETRY_LEFT_RIGHT_CIRCULAR_ARROW,
  curvedRightArrow: ShapeGeometry.SHAPE_GEOMETRY_CURVED_RIGHT_ARROW,
  curvedLeftArrow: ShapeGeometry.SHAPE_GEOMETRY_CURVED_LEFT_ARROW,
  curvedUpArrow: ShapeGeometry.SHAPE_GEOMETRY_CURVED_UP_ARROW,
  curvedDownArrow: ShapeGeometry.SHAPE_GEOMETRY_CURVED_DOWN_ARROW,
  swooshArrow: ShapeGeometry.SHAPE_GEOMETRY_SWOOSH_ARROW,
  cube: ShapeGeometry.SHAPE_GEOMETRY_CUBE,
  can: ShapeGeometry.SHAPE_GEOMETRY_CAN,
  lightningBolt: ShapeGeometry.SHAPE_GEOMETRY_LIGHTNING_BOLT,
  heart: ShapeGeometry.SHAPE_GEOMETRY_HEART,
  sun: ShapeGeometry.SHAPE_GEOMETRY_SUN,
  moon: ShapeGeometry.SHAPE_GEOMETRY_MOON,
  smileyFace: ShapeGeometry.SHAPE_GEOMETRY_SMILEY_FACE,
  irregularSeal1: ShapeGeometry.SHAPE_GEOMETRY_IRREGULAR_SEAL1,
  irregularSeal2: ShapeGeometry.SHAPE_GEOMETRY_IRREGULAR_SEAL2,
  foldedCorner: ShapeGeometry.SHAPE_GEOMETRY_FOLDED_CORNER,
  bevel: ShapeGeometry.SHAPE_GEOMETRY_BEVEL,
  frame: ShapeGeometry.SHAPE_GEOMETRY_FRAME,
  halfFrame: ShapeGeometry.SHAPE_GEOMETRY_HALF_FRAME,
  corner: ShapeGeometry.SHAPE_GEOMETRY_CORNER,
  diagStripe: ShapeGeometry.SHAPE_GEOMETRY_DIAG_STRIPE,
  chord: ShapeGeometry.SHAPE_GEOMETRY_CHORD,
  arc: ShapeGeometry.SHAPE_GEOMETRY_ARC,
  leftBracket: ShapeGeometry.SHAPE_GEOMETRY_LEFT_BRACKET,
  rightBracket: ShapeGeometry.SHAPE_GEOMETRY_RIGHT_BRACKET,
  leftBrace: ShapeGeometry.SHAPE_GEOMETRY_LEFT_BRACE,
  rightBrace: ShapeGeometry.SHAPE_GEOMETRY_RIGHT_BRACE,
  bracketPair: ShapeGeometry.SHAPE_GEOMETRY_BRACKET_PAIR,
  bracePair: ShapeGeometry.SHAPE_GEOMETRY_BRACE_PAIR,
  straightConnector1: ShapeGeometry.SHAPE_GEOMETRY_STRAIGHT_CONNECTOR1,
  bentConnector2: ShapeGeometry.SHAPE_GEOMETRY_BENT_CONNECTOR2,
  bentConnector3: ShapeGeometry.SHAPE_GEOMETRY_BENT_CONNECTOR3,
  bentConnector4: ShapeGeometry.SHAPE_GEOMETRY_BENT_CONNECTOR4,
  bentConnector5: ShapeGeometry.SHAPE_GEOMETRY_BENT_CONNECTOR5,
  curvedConnector2: ShapeGeometry.SHAPE_GEOMETRY_CURVED_CONNECTOR2,
  curvedConnector3: ShapeGeometry.SHAPE_GEOMETRY_CURVED_CONNECTOR3,
  curvedConnector4: ShapeGeometry.SHAPE_GEOMETRY_CURVED_CONNECTOR4,
  curvedConnector5: ShapeGeometry.SHAPE_GEOMETRY_CURVED_CONNECTOR5,
  callout1: ShapeGeometry.SHAPE_GEOMETRY_CALLOUT1,
  callout2: ShapeGeometry.SHAPE_GEOMETRY_CALLOUT2,
  callout3: ShapeGeometry.SHAPE_GEOMETRY_CALLOUT3,
  accentCallout1: ShapeGeometry.SHAPE_GEOMETRY_ACCENT_CALLOUT1,
  accentCallout2: ShapeGeometry.SHAPE_GEOMETRY_ACCENT_CALLOUT2,
  accentCallout3: ShapeGeometry.SHAPE_GEOMETRY_ACCENT_CALLOUT3,
  borderCallout1: ShapeGeometry.SHAPE_GEOMETRY_BORDER_CALLOUT1,
  borderCallout2: ShapeGeometry.SHAPE_GEOMETRY_BORDER_CALLOUT2,
  borderCallout3: ShapeGeometry.SHAPE_GEOMETRY_BORDER_CALLOUT3,
  accentBorderCallout1: ShapeGeometry.SHAPE_GEOMETRY_ACCENT_BORDER_CALLOUT1,
  accentBorderCallout2: ShapeGeometry.SHAPE_GEOMETRY_ACCENT_BORDER_CALLOUT2,
  accentBorderCallout3: ShapeGeometry.SHAPE_GEOMETRY_ACCENT_BORDER_CALLOUT3,
  wedgeRectCallout: ShapeGeometry.SHAPE_GEOMETRY_WEDGE_RECT_CALLOUT,
  wedgeRoundRectCallout: ShapeGeometry.SHAPE_GEOMETRY_WEDGE_ROUND_RECT_CALLOUT,
  wedgeEllipseCallout: ShapeGeometry.SHAPE_GEOMETRY_WEDGE_ELLIPSE_CALLOUT,
  cloudCallout: ShapeGeometry.SHAPE_GEOMETRY_CLOUD_CALLOUT,
  cloud: ShapeGeometry.SHAPE_GEOMETRY_CLOUD,
  ribbon: ShapeGeometry.SHAPE_GEOMETRY_RIBBON,
  ribbon2: ShapeGeometry.SHAPE_GEOMETRY_RIBBON2,
  ellipseRibbon: ShapeGeometry.SHAPE_GEOMETRY_ELLIPSE_RIBBON,
  ellipseRibbon2: ShapeGeometry.SHAPE_GEOMETRY_ELLIPSE_RIBBON2,
  leftRightRibbon: ShapeGeometry.SHAPE_GEOMETRY_LEFT_RIGHT_RIBBON,
  verticalScroll: ShapeGeometry.SHAPE_GEOMETRY_VERTICAL_SCROLL,
  horizontalScroll: ShapeGeometry.SHAPE_GEOMETRY_HORIZONTAL_SCROLL,
  wave: ShapeGeometry.SHAPE_GEOMETRY_WAVE,
  doubleWave: ShapeGeometry.SHAPE_GEOMETRY_DOUBLE_WAVE,
  plus: ShapeGeometry.SHAPE_GEOMETRY_PLUS,
  flowChartProcess: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_PROCESS,
  flowChartDecision: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_DECISION,
  flowChartInputOutput: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_INPUT_OUTPUT,
  flowChartPredefinedProcess:
    ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_PREDEFINED_PROCESS,
  flowChartInternalStorage:
    ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_INTERNAL_STORAGE,
  flowChartDocument: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_DOCUMENT,
  flowChartMultidocument: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_MULTIDOCUMENT,
  flowChartTerminator: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_TERMINATOR,
  flowChartPreparation: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_PREPARATION,
  flowChartManualInput: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_MANUAL_INPUT,
  flowChartManualOperation:
    ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_MANUAL_OPERATION,
  flowChartConnector: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_CONNECTOR,
  flowChartPunchedCard: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_PUNCHED_CARD,
  flowChartPunchedTape: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_PUNCHED_TAPE,
  flowChartSummingJunction:
    ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_SUMMING_JUNCTION,
  flowChartOr: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_OR,
  flowChartCollate: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_COLLATE,
  flowChartSort: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_SORT,
  flowChartExtract: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_EXTRACT,
  flowChartMerge: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_MERGE,
  flowChartOfflineStorage:
    ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_OFFLINE_STORAGE,
  flowChartOnlineStorage:
    ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_ONLINE_STORAGE,
  flowChartMagneticTape: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_MAGNETIC_TAPE,
  flowChartMagneticDisk: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_MAGNETIC_DISK,
  flowChartDatabase: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_MAGNETIC_DISK,
  flowChartMagneticDrum: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_MAGNETIC_DRUM,
  flowChartDisplay: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_DISPLAY,
  flowChartDelay: ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_DELAY,
  flowChartAlternateProcess:
    ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_ALTERNATE_PROCESS,
  flowChartOffpageConnector:
    ShapeGeometry.SHAPE_GEOMETRY_FLOW_CHART_OFFPAGE_CONNECTOR,
  actionButtonBlank: ShapeGeometry.SHAPE_GEOMETRY_ACTION_BUTTON_BLANK,
  actionButtonHome: ShapeGeometry.SHAPE_GEOMETRY_ACTION_BUTTON_HOME,
  actionButtonHelp: ShapeGeometry.SHAPE_GEOMETRY_ACTION_BUTTON_HELP,
  actionButtonInformation:
    ShapeGeometry.SHAPE_GEOMETRY_ACTION_BUTTON_INFORMATION,
  actionButtonForwardNext:
    ShapeGeometry.SHAPE_GEOMETRY_ACTION_BUTTON_FORWARD_NEXT,
  actionButtonBackPrevious:
    ShapeGeometry.SHAPE_GEOMETRY_ACTION_BUTTON_BACK_PREVIOUS,
  actionButtonEnd: ShapeGeometry.SHAPE_GEOMETRY_ACTION_BUTTON_END,
  actionButtonBeginning: ShapeGeometry.SHAPE_GEOMETRY_ACTION_BUTTON_BEGINNING,
  actionButtonReturn: ShapeGeometry.SHAPE_GEOMETRY_ACTION_BUTTON_RETURN,
  actionButtonDocument: ShapeGeometry.SHAPE_GEOMETRY_ACTION_BUTTON_DOCUMENT,
  actionButtonSound: ShapeGeometry.SHAPE_GEOMETRY_ACTION_BUTTON_SOUND,
  actionButtonMovie: ShapeGeometry.SHAPE_GEOMETRY_ACTION_BUTTON_MOVIE,
  gear6: ShapeGeometry.SHAPE_GEOMETRY_GEAR6,
  gear9: ShapeGeometry.SHAPE_GEOMETRY_GEAR9,
  funnel: ShapeGeometry.SHAPE_GEOMETRY_FUNNEL,
  mathPlus: ShapeGeometry.SHAPE_GEOMETRY_MATH_PLUS,
  mathMinus: ShapeGeometry.SHAPE_GEOMETRY_MATH_MINUS,
  mathMultiply: ShapeGeometry.SHAPE_GEOMETRY_MATH_MULTIPLY,
  mathDivide: ShapeGeometry.SHAPE_GEOMETRY_MATH_DIVIDE,
  mathEqual: ShapeGeometry.SHAPE_GEOMETRY_MATH_EQUAL,
  mathNotEqual: ShapeGeometry.SHAPE_GEOMETRY_MATH_NOT_EQUAL,
  cornerTabs: ShapeGeometry.SHAPE_GEOMETRY_CORNER_TABS,
  squareTabs: ShapeGeometry.SHAPE_GEOMETRY_SQUARE_TABS,
  plaqueTabs: ShapeGeometry.SHAPE_GEOMETRY_PLAQUE_TABS,
  chartX: ShapeGeometry.SHAPE_GEOMETRY_CHART_X,
  chartStar: ShapeGeometry.SHAPE_GEOMETRY_CHART_STAR,
  chartPlus: ShapeGeometry.SHAPE_GEOMETRY_CHART_PLUS,
  custom: ShapeGeometry.SHAPE_GEOMETRY_CUSTOM,
  textbox: ShapeGeometry.SHAPE_GEOMETRY_RECT,
} as const;
