// Restored from ref/webview/assets/workbook-C49Dgk1_.js
// Stage-3 wave-1: presentation/chart protobuf ↔ camelCase name bridges.

import { dr as patternTypeEnum } from "../presentation-protobuf";

export const patternTypeNameToProto = {
  none: patternTypeEnum.PATTERN_TYPE_NONE,
  solid: patternTypeEnum.PATTERN_TYPE_SOLID,
  mediumGray: patternTypeEnum.PATTERN_TYPE_MEDIUM_GRAY,
  darkGray: patternTypeEnum.PATTERN_TYPE_DARK_GRAY,
  lightGray: patternTypeEnum.PATTERN_TYPE_LIGHT_GRAY,
  darkHorizontal: patternTypeEnum.PATTERN_TYPE_DARK_HORIZONTAL,
  darkVertical: patternTypeEnum.PATTERN_TYPE_DARK_VERTICAL,
  darkDown: patternTypeEnum.PATTERN_TYPE_DARK_DOWN,
  darkUp: patternTypeEnum.PATTERN_TYPE_DARK_UP,
  darkGrid: patternTypeEnum.PATTERN_TYPE_DARK_GRID,
  darkTrellis: patternTypeEnum.PATTERN_TYPE_DARK_TRELLIS,
  lightHorizontal: patternTypeEnum.PATTERN_TYPE_LIGHT_HORIZONTAL,
  lightVertical: patternTypeEnum.PATTERN_TYPE_LIGHT_VERTICAL,
  lightDown: patternTypeEnum.PATTERN_TYPE_LIGHT_DOWN,
  lightUp: patternTypeEnum.PATTERN_TYPE_LIGHT_UP,
  lightGrid: patternTypeEnum.PATTERN_TYPE_LIGHT_GRID,
  lightTrellis: patternTypeEnum.PATTERN_TYPE_LIGHT_TRELLIS,
  gray125: patternTypeEnum.PATTERN_TYPE_GRAY125,
  gray0625: patternTypeEnum.PATTERN_TYPE_GRAY0625,
  percent5: patternTypeEnum.PATTERN_TYPE_PERCENT_5,
  percent10: patternTypeEnum.PATTERN_TYPE_PERCENT_10,
  percent20: patternTypeEnum.PATTERN_TYPE_PERCENT_20,
  percent25: patternTypeEnum.PATTERN_TYPE_PERCENT_25,
  percent30: patternTypeEnum.PATTERN_TYPE_PERCENT_30,
  percent40: patternTypeEnum.PATTERN_TYPE_PERCENT_40,
  percent50: patternTypeEnum.PATTERN_TYPE_PERCENT_50,
  percent60: patternTypeEnum.PATTERN_TYPE_PERCENT_60,
  percent70: patternTypeEnum.PATTERN_TYPE_PERCENT_70,
  percent75: patternTypeEnum.PATTERN_TYPE_PERCENT_75,
  percent80: patternTypeEnum.PATTERN_TYPE_PERCENT_80,
  percent90: patternTypeEnum.PATTERN_TYPE_PERCENT_90,
  horizontal: patternTypeEnum.PATTERN_TYPE_HORIZONTAL,
  vertical: patternTypeEnum.PATTERN_TYPE_VERTICAL,
  narrowHorizontal: patternTypeEnum.PATTERN_TYPE_NARROW_HORIZONTAL,
  narrowVertical: patternTypeEnum.PATTERN_TYPE_NARROW_VERTICAL,
  dashedHorizontal: patternTypeEnum.PATTERN_TYPE_DASHED_HORIZONTAL,
  dashedVertical: patternTypeEnum.PATTERN_TYPE_DASHED_VERTICAL,
  cross: patternTypeEnum.PATTERN_TYPE_CROSS,
  largeGrid: patternTypeEnum.PATTERN_TYPE_LARGE_GRID,
  smallGrid: patternTypeEnum.PATTERN_TYPE_SMALL_GRID,
  dotGrid: patternTypeEnum.PATTERN_TYPE_DOT_GRID,
  downwardDiagonal: patternTypeEnum.PATTERN_TYPE_DOWNWARD_DIAGONAL,
  upwardDiagonal: patternTypeEnum.PATTERN_TYPE_UPWARD_DIAGONAL,
  wideDownwardDiagonal: patternTypeEnum.PATTERN_TYPE_WIDE_DOWNWARD_DIAGONAL,
  wideUpwardDiagonal: patternTypeEnum.PATTERN_TYPE_WIDE_UPWARD_DIAGONAL,
  dashedDownwardDiagonal: patternTypeEnum.PATTERN_TYPE_DASHED_DOWNWARD_DIAGONAL,
  dashedUpwardDiagonal: patternTypeEnum.PATTERN_TYPE_DASHED_UPWARD_DIAGONAL,
  diagonalCross: patternTypeEnum.PATTERN_TYPE_DIAGONAL_CROSS,
  smallCheck: patternTypeEnum.PATTERN_TYPE_SMALL_CHECK,
  largeCheck: patternTypeEnum.PATTERN_TYPE_LARGE_CHECK,
  smallConfetti: patternTypeEnum.PATTERN_TYPE_SMALL_CONFETTI,
  largeConfetti: patternTypeEnum.PATTERN_TYPE_LARGE_CONFETTI,
  horizontalBrick: patternTypeEnum.PATTERN_TYPE_HORIZONTAL_BRICK,
  diagonalBrick: patternTypeEnum.PATTERN_TYPE_DIAGONAL_BRICK,
  solidDiamond: patternTypeEnum.PATTERN_TYPE_SOLID_DIAMOND,
  openDiamond: patternTypeEnum.PATTERN_TYPE_OPEN_DIAMOND,
  dottedDiamond: patternTypeEnum.PATTERN_TYPE_DOTTED_DIAMOND,
  plaid: patternTypeEnum.PATTERN_TYPE_PLAID,
  sphere: patternTypeEnum.PATTERN_TYPE_SPHERE,
  weave: patternTypeEnum.PATTERN_TYPE_WEAVE,
  divot: patternTypeEnum.PATTERN_TYPE_DIVOT,
  shingle: patternTypeEnum.PATTERN_TYPE_SHINGLE,
  wave: patternTypeEnum.PATTERN_TYPE_WAVE,
  trellis: patternTypeEnum.PATTERN_TYPE_TRELLIS,
  zigZag: patternTypeEnum.PATTERN_TYPE_ZIG_ZAG,
} as const;
